### ISSUE TITLE
Spork gem can't actually be installed

### ISSUE THREAD

**Issue by scudco** [sporkrb/spork#1]
$ sudo gem install timcharper-spork --source http://gems.github.com
ERROR:  could not find gem timcharper-spork locally or in a repository

http://hasmygembuiltyet.org/timcharper/spork

I was able to install it locally by cloning and then I found the culprit in the gemspec. Seems you can't use things like Dir['lib/*_/_.rb'] when running with the SAFE level at 3 like github does.

Here's my patch 
http://github.com/scudco/spork/commit/c31c8ea83da1ca2acc3fc74bd59c91aeca2dcde4

**Comment by timcharper** [comment]
Thank you for this :)

I ended up switching over to Jeweler, and upload my gems to rubyforge.  (gem install  timcharper-spork just doesn't feel as legit as gem install spork).

Tim

**Comment by timcharper** [comment]
(correction - Ben Mabey switched me over to Jeweler :) )
