### ISSUE TITLE
windows no such file to load -- spork

### ISSUE THREAD

**Issue by blimey85** [sporkrb/spork#100]
I'm running Rails 3.0.5 with Ruby 1.9.2 on Windows 7 32bit and when I try to start spork I get the following:

C:\rails_projects\another_app>spork rspec
Using RSpec
  -- Rinda Ring Server listening for connections...

  -- Starting to fill pool...
     Wait until at least one slave is provided before running tests...
  *\* CTRL+BREAK to stop Spork and kill all ruby slave processes **
Spork is ready and listening on 8989!
   -- build slave 1...
   -- build slave 2...
Preloading Rails environment
Preloading Rails environment
Loading Spork.prefork block...
C:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:239:in `require': no such file to load -- spork (LoadError)
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:239:in`block in require'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:225:in `block in load_dependency'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:596:in`new_constants_in'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:225:in `load_dependency'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:239:in`require'
        from C:/rails_projects/another_app/spec/spec_helper.rb:2:in `<top (required)>'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:235:in`load'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:235:in `block in load'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:225:in`block in load_dependency'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:596:in `new_constants_in'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:225:in`load_dependency'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:235:in `load'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/spork-0.9.0.rc4/lib/spork/test_framework.rb:138:in`block (2 levels) in preload'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/spork-0.9.0.rc4/lib/spork/app_framework/rails.rb:8:in `preload'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/spork-0.9.0.rc4/lib/spork/test_framework.rb:134:in`block in preload'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/spork-0.9.0.rc4/lib/spork.rb:61:in `exec_prefork'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/spork-0.9.0.rc4/lib/spork/test_framework.rb:120:in`preload'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/spork-0.9.0.rc4/lib/spork/run_strategy/magazine/magazine_slave.rb:27:in `preload'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/spork-0.9.0.rc4/lib/spork/run_strategy/magazine/magazine_slave.rb:15:in`initialize'
        from magazine_slave_provider.rb:21:in `new'
        from magazine_slave_provider.rb:21:in`<main>'

Any idea how I can solve this? I saw there was a closed issue with a different file loading issue but nothing I could find about this.

C:\rails_projects\another_app>gem list -d spork

**\* LOCAL GEMS ***

spork (0.9.0.rc4)
    Authors: Tim Harper, Donald Parish
    Rubyforge: http://rubyforge.org/projects/spork
    Homepage: http://github.com/timcharper/spork
    Installed at: C:/Ruby192/lib/ruby/gems/1.9.1

```
spork
```

**Comment by blimey85** [comment]
I figured it out. I added spork to my gemfile, had Rubymine attach the gem to my project, and then it worked just fine.

**Comment by rdp** [comment]
how to reproduce?
-r

On Thu, Apr 7, 2011 at 5:46 PM, blimey85
reply@reply.github.com
wrote:

**Comment by blimey85** [comment]
Install it via "gem install spork" and then try to run it inside of a project folder without first adding it to the gemfile. That's what caused the issue for me. Once I added it to the gemfile and had Rubymine attach it to the project, it worked fine. Although it's not as fast as I expected. Running a simple suite of tests in RSpec it takes 31 seconds without spork and 10.5 with spork. Rails is very slow to start on my system for some reason, but I figured with spork it would be quite a bit faster than 10.5 seconds. I'm pretty new to rails though so maybe I'm overlooking something obvious.

**Comment by rdp** [comment]
you can speed up rails loading (I believe) on windows by using the faster_require gem

**Comment by blimey85** [comment]
Thanks for the info. I'll give that a try tonight and see if it helps. :)

**Comment by rdp** [comment]
oops just released an updated version of faster_require that works
better with 1.9.2 last night.
Sorry for the bugs.
-r

On Fri, Apr 8, 2011 at 10:05 AM, blimey85
reply@reply.github.com
wrote:
