### ISSUE TITLE
Need a guide to when to restart Spork and a quick way of doing so

### ISSUE THREAD

**Issue by snoblenet** [sporkrb/spork#102]
I'm finding I have to quit and restart Spork after making some changes to my code that I expect to be loaded dynamically.

I expected to have to restart Spork after, say, running new migrations, but sometimes I have to restart it after modifying a method in a controller.

It would be great if the wiki provided a complete guide to when one needs to restart spork.

It would also be great if there was a command line tool for restarting spork in one step.

**Comment by timcharper** [comment]
Thanks for raising this. It's important enough to be documented in the README.  (which I have just done).  I hope this helps!

https://github.com/timcharper/spork/
