### ISSUE TITLE
custom classes in config.autoload_paths are not loaded (spork >0.9rc5)

### ISSUE THREAD

**Issue by fwoeck** [sporkrb/spork#110]
Hi, we have classes in custom paths, like this in application.rb:

  %w(system users workspaces).each do |dir|
    config.autoload_paths << "#{config.root}/app/models/#{dir}"
  end

in a Rails307-app. The class names do not follow the naming convention that contains the dir name in the class name.

This works pretty well with spork 0.84 with the ActiveSupport::Dependencies hack.
With the latest spork commit version, these files are not loaded at all, it seems.
Thanks for any helpful hints on this,
--Frank

**Comment by timcharper** [comment]
Do you mean they aren't preloaded? Or they aren't found when you try to autoload them?

**Comment by timcharper** [comment]
I would be surprised if spork 0.8.4 worked as expected with Rails 3.  It most likely won't.

**Comment by timcharper** [comment]
Hmm... I can't reproduce this, it's working here. I wrote an integration test to test it... maybe you can run it and see if it passes for you too?

https://github.com/timcharper/spork/commit/680809fc319783be2542c1f90badd2d4b31a0bb0

**Comment by fwoeck** [comment]
Hi Tim, thanks for your work! Apparently I have a

  ActiveSupport::Dependencies.clear if Spork.using_spork?

in env.rb and spec_helper.rb and

```
if Rails.env.test? && defined?(Spork) && Spork.using_spork?
  initializer :after => :initialize_dependency_mechanism do
    ActiveSupport::Dependencies.mechanism = :load
  end
end
```

in the application.rb - and 0.8.4 works perfectly with rails307.
When I use 0.9rc5 rspec complains that the classes defined in my autoload_paths are unknown, so I assume they aren't preloaded. I'll try your spec!
--Frank
