### ISSUE TITLE
Can't exclude rspec tags with spork

### ISSUE THREAD

**Issue by cblavier** [sporkrb/spork#115]
Hello,
I'm running a Rails 3.0.7 with Rspec 2.6 and Spork 0.9.0.rc7 and I can't exclude rspec tags when using drb on spork.
When I run `rspec spec --tag ~slow`, spork server only prompt this : `Running tests with args ["--color", "spec"]`

It works whenever I want to include tags,  or if I exclude tags without using drb/spork.

Thank for any kind of help

**Comment by cblavier** [comment]
Can someone give me a clue of where I should start looking in the source-code ? I'll try to get it fixed

**Comment by trkoch** [comment]
I noticed `--tag key:val` is interpreted as `{:key => true}` while it should be `{:key => "val"}`. When running without spork, rspec behaves correctly.
