### ISSUE TITLE
spork's dependency on rake (when building native extensions) results in rake 0.9.0 being installed

### ISSUE THREAD

**Issue by dchelimsky** [sporkrb/spork#119]
Per the session below, installing spork causes rake to be installed with no version constraint. This is happening due to line 9 in https://github.com/timcharper/spork/blob/master/ext/mkrf_conf.rb.

Since the release of rake-0.9.0, this means installing spork installs rake-0.9.0, which breaks `rake xxx` for any application that has a dependency (direct or downstream) on rake-0.8.7. In our case, it didn't break any deployments, because spork is in a development group in Gemfiles, but it did break all of our ci builds.

Clearly this has to change. One possibility would be to make rake a formal dependency in the gemspec with a proper version constraint ('~> 0.8.7') so that bundler and/or rubygems can install the proper version of rake for the environment, but I'm not sure if that would work in all cases or if it's the best solution.

```
$ gem -v
1.8.4
$ ruby -v
ruby 1.9.2p0 (2010-08-18 revision 29036) [x86_64-darwin10.4.0]
$ gem list

*** LOCAL GEMS ***


[bundlertest]$ gem install spork
Fetching: spork-0.8.4.gem (100%)
Building native extensions.  This could take a while...
Successfully installed spork-0.8.4
1 gem installed
[bundlertest]$ gem list rake

*** LOCAL GEMS ***

rake (0.9.0)
$ gem spec spork | grep rake
$
```

**Comment by dchelimsky** [comment]
FYI - I had reported this initially to bundler(https://github.com/carlhuda/bundler/issues/1204), then rubygems (http://rubyforge.org/tracker/index.php?func=detail&aid=29229&group_id=126&atid=575).

**Comment by zmoazeni** [comment]
It's sad that a breakage on rake is causing this kind of headache. Especially considering how widely used it is. Still, a good catch David.

I was wondering how the latest rake got installed on my system.

**Comment by drnic** [comment]
Could rvm be installing rake for you? (@wayneeseguin)

**Comment by dchelimsky** [comment]
@drnic - it's not rvm. Look at https://github.com/timcharper/spork/blob/master/ext/mkrf_conf.rb - that's the culprit.

**Comment by dchelimsky** [comment]
@zmoazeni thanks go to my coworker @kcowgill who found the rake dep in https://github.com/timcharper/spork/blob/master/ext/mkrf_conf.rb. Before he did I had reported this to two other places that weren't the source of the problem :)

**Comment by tenderlove** [comment]
Judging from the mkrf file that @dchelimsky is pointing to, I think the real solution for this gem is to ship platform specific versions.  Each platform specific version can have particular dependencies.  So, make the win32 gem depend on `win32-process`, where the normal `ruby` platform does not.

**Comment by dchelimsky** [comment]
@tenderlove - you mean express those deps in the gemspec, right?

**Comment by luislavena** [comment]
@dchelimsky, yes, @tenderlove is correct, that will be the best solution.

For example recently we had a exchange with libnotify gem author on something similar:

http://help.rubygems.org/discussions/problems/608-wrong-version-for-libnotify

libnotify defined ffi dependency for the ruby platform but didn't for the rubinius one. That solved the issue of ffi gem not been able to install on rubinius.

(actually ffi gem installation on rubinius should be a noop, a shim gem or something will be great)

Anyhow, you take one single gemspec, you then modify it just to change platform and dependencies and generate multiple gems from it.

Of course that is something Bundler will not support in the gemspec (or the generated gemlock file) from the git repository directly but will work for mere mortals installing gems.

**Comment by tenderlove** [comment]
@dchelimsky correct.  It requires shipping three gems.  One targeted at the `ruby` platform that has no dependencies.  One targeted at `x86-mswin32` and one targeted at `x86-mingw32` that depend on `win32-process`.

I'm not totally clear on why this file is installing rake, but if `win32-process` requires rake to compile, then _it_ should depend on rake.

**Comment by luislavena** [comment]
@tenderlove no, win32-process do not depend on rake, is the mkrf itself:

https://github.com/timcharper/spork/blob/master/ext/mkrf_conf.rb#L7-12

I must say this mkrf file is a box full of surprises!

**Comment by tenderlove** [comment]
@luislavena this is generally why we should never point bundler at git repositories.  But that is a different issue than this.  ;-)

Also, is there a platform that will pick up both mswin32 _and_ mingw32?  Or do they need to ship both?

**Comment by luislavena** [comment]
@tenderlove, no, they need both :(

That is because Visual Studio builds of ruby uses mswin and MinGW builds uses mingw... :-P

**Comment by dchelimsky** [comment]
@zmoazeni the problem here is not that rake breaks compatibility. Yes, it does in some cases, but not in most cases. The root problem is a catch 22: we depend on rake to run things that also depend on rake. Rubygems won't activate two versions of rake, so when we have 0.9 installed and run 'rake xxx', rubygems activates 0.9 and then complains when the thing we're running depends on rake 0.8. In the long run, we should be specifying the version of rake to run from the start, but we're not accustomed to doing that: `rake _0.8.7_ xxx` or `bundle exec rake xxx` when using bundler.

This problem is exacerbated by the fact that we put Bundler.setup in our Rakefiles. The intent here is to let bundler handle everything for us, but it causes bundler to enter the game after rake 0.9 has already been activated. I'm sure nobody thought about this because we've been using the same version of rake (0.8.7) for bundler's entire lifetime.

**Comment by zmoazeni** [comment]
@dchelimsky Thanks for the heads up and detailed response.

**Comment by dchelimsky** [comment]
@zmoazeni - one thing I left out is that if bundler users were in the habit of running `bundle exec rake` (or `bin/rake` after running `bundle install --binstubs`), this would not be an issue. My recollection is that the bundler team was recommending these practices early on, but users complained about having to type all those extra characters, so the Rakefile generated by `rails new` included `Bundler.setup`. I could be wrong about that, but I'm pretty sure that's how it went. And so it goes.

**Comment by zmoazeni** [comment]
@dchelimsky running `bundle exec rake ...` has been my fix. That and having an alias `alias be = "bundle exec"` makes it a little easier to swallow `be rake ...` but not exactly newbie friendly which affected one of my coworkers teaching an intro to ruby class this week.

**Comment by dchelimsky** [comment]
@zmoazeni my preference is `bundle install --binstubs` and `bin/rake`. It's more characters than `be rake`, but I think it tells a better story: "use the version of rake built into this application".

**Comment by timcharper** [comment]
Sigh, that code always kind of bugged me.  I axed it.  It will make things a little less convenient for windows users, but it just wasn't worth it.  In windows you have to manually install the extra dependency required (win32-process), with spork showing a message instructing the user to do so it's missing, similar to how active_support yells at you for i18n.

I wish there were a better way to do conditional dependencies in gems, but perhaps it is just a bad idea all around.

**Comment by timcharper** [comment]
(I back-ported the fix to the 0.8.x branch, the first back port of a fix made since 0.9.0 development).

**Comment by luislavena** [comment]
@timchapter You can use the post_install_message which will be presented to the user after gem installation.

**Comment by dchelimsky** [comment]
@timcharper - thanks for jumping on this!

**Comment by timcharper** [comment]
@luislavena - that's a good idea, can the post_install_message be conditional?  The way gemspecs are rendered to YAML, it makes any kind of logic impossible other than logic embedded in mkrf (which is why I sort of hijacked it on recommendation of another rubyist).

@tenderlove - once mkrf finishes running, rubygems will run the emitted Rakefile. Or something like that. I can't remember. It's an ugly hack and I should have killed it a year ago.

**Comment by luislavena** [comment]
@timcharper to our bad, no conditional on the message, you will need to generate different gems for each platform (and have each one indicating it's own depedencies).

You can achieve this using `Gem::PackageTask` (provided by RubyGems) and duplication of the gemspec just to change the platform and post install message. Then for you to generate the gems will be a matter of just saying `rake gem`

If you would like that (just to avoid the pain for Windows users (which includes me) I can send you a pull request with what I'm mentioning here.

**Comment by timcharper** [comment]
I'm not sure the pain is bad enough to warrant publishing multiple versions of gems, could be especially painful in a cross-platform development environment.  Is it really bad to have to be reminded to add an extra dependency for windows ruby?

It can be further confusing because ruby 1.9.1 on windows provide Process methods that render the win32-process gem no longer a necessary dependency...

I am leaning towards just leaving it how it is.  If people complain really loudly, then I'd consider the multiple gem approach, but right now I'm hesitant to go that route.

**Comment by luislavena** [comment]
@timcharper agree, is just annoying that you think you're done and **then** you need to install another gem :-P

But that is just 1.9.1 or lower. Anyhow, Bundler chews post install messages and for those using bundler, the lockfile can be really a problem.

Drop me a line if you hear people complaining about this, will love to help :-)

**Comment by timcharper** [comment]
@luislavena I didn't realize that by using different gem platforms you could push the gem as the same name (was thinking it was going to end up being "spork-win32" and "spork".  That's why I was so allergic to the idea.  Aaron Patterson sent me a pull request and showed me the light, so I ran with it.

Thanks everyone.
