### ISSUE TITLE
Getting DEPRECATION WARNING related to Rspec and lib/spork.rb.

### ISSUE THREAD

**Issue by jasnow** [sporkrb/spork#131]
Ran "rake spec" with Rails 3.1.0.rc4 on Rails Tutorial's sample_3_1 (ported to 3.1).
Getting DEPRECATION WARNING related to Rspec and lib/spork.rb.
Example in my Gist: https://gist.github.com/1102778

---

DEPRECATION WARNING: you are using a deprecated constant that will
be removed from a future version of RSpec.

~/.rvm/gems/ruby-1.9.2-p180@rails31/gems/spork-0.9.0.rc9/lib/spork.rb:24:in `prefork'
- Rspec is deprecated.
- RSpec is the new top-level module in RSpec-2

*****************************************************************```

**Comment by jasnow** [comment]
This is how I got spork. In my Gemfile,
gem 'spork', :git => "git://github.com/chrismdp/spork.git"

**Comment by nofxx** [comment]
This is fixed in #c4a3819b83b862aa1 , support rspec versions 1.x and >= 2 .

**Comment by jasnow** [comment]
nofxx - where is this #c4a3819b83b862aa1 ? I am still getting this warning

**Comment by nofxx** [comment]
It's the commit hashtag. But it's ok in spork-0.9.0.rc9 too.  
Should be something in your code, spec_helper....

**Comment by jasnow** [comment]
Changed one character in my spec/spec_helper as you suggested. Warning went away. Thanks.
