### ISSUE TITLE
DRb::DRbConnError any time RSpec tries to use Spork

### ISSUE THREAD

**Issue by indirect** [sporkrb/spork#133]
Any time I run Spork and attempt to connect to it via `rspec --drb`, RSpec exits with an exception and Spork throws a DRb::DRbConnError. I am pretty much at a loss as to what could be going on here. Any ideas?

```
Running tests with args ["--color", "spec/views/servers/access_tokens.xml.builder_spec.rb"]...
Exception encountered: #<DRb::DRbConnError: druby://localhost:51542 - #<Errno::ECONNREFUSED: Connection refused - connect(2)>>
```

Full output from both Spork and RSpec commands here: https://gist.github.com/318c12c94b8d7740a3ba

**Comment by rdp** [comment]
when does the spork command die (I assume it does)?

**Comment by indirect** [comment]
Nope, it doesn't. I can run rspec repeatedly without restarting spork and get the same errors every time.

**Comment by rdp** [comment]
is it binding to port 51542  ?

**Comment by indirect** [comment]
No. The gist I made and linked to above contains all of the output from Spork, including the line `Spork is ready and listening on 8989!`

**Comment by indirect** [comment]
Investigated this some more today, and the port number changes every time I try to run `rspec --drb`. I think that means it's a drb error? Maybe? Anyone have an idea?

**Comment by coryschires** [comment]
I am having this same issue. I'll be looking into it. If anyone has any clues, please let me know.

**Comment by indirect** [comment]
It started for me once I had upgraded my laptop to OS X Lion (10.7). The same error happens in the same project on a new machine that shipped with a clean install of Lion. I haven't had time to investigate further yet.

**Comment by indirect** [comment]
Well, I have at least tracked this down to the point where I'm pretty sure this is a bug in Spork, and not in Lion or DRb.

I have created a FakeSpork class and set it up as a DRb server for RSpec to run against, with the code and output included below. Since everything (including sending output back to the RSpec drb runner) works correctly when Spork and forking craziness isn't involved, I can only conjecture that Spork is somehow preventing itself from connecting back to the client process correctly as in the errors listed above ↑.

I would love to hear anyone's thoughts on this, especially if they have any suggestions as to where to start looking for the issue inside the forking part of Spork. I miss being able to run my tests quickly. :( Thanks!

``` ruby
# fakespork.rb
require 'drb'

module FakeSpork
  def self.run(args, stderr, stdout)
    puts "run called with: #{args.inspect}"
    stdout.puts "this proves I can connect back to the client and send it things!"
  end
end

DRb.start_service("druby://127.0.0.1:8989", FakeSpork)
puts "FakeSpork ready for action on port 8989!"
DRb.thread.join
```

After running `ruby fakespork.rb`, I then run `rspec --drb --color spec` in another terminal, which produces the expected output, without any errors:

```
$ ruby ~/fake_spork.rb 
FakeSpork ready for action on port 8989!
run called with: ["--color", "spec"]
```

```
$ bundle exec rspec --color --drb spec
this proves I can connect back to the client and send it things!
```

**Comment by indirect** [comment]
Well, holy shit. Several hours later, I kept expanding FakeSpork until it did all the things real Spork did, and it turned out that things stopped working once the Rails app was getting preloaded.

After diving all the way down into that, it turned out things stopped working when a specific gem got loaded by bundler: always_verify_ssl_certificates. That gem does deep and nasty monkeypatching to the Net::HTTP class, and (apparently) has the side effect of completely stopping DRb from working at all.

Sorry for casting blame on Spork, here, as it works perfectly as soon as I take that gem out of my Gemfile. Hopefully this will help other people with the same error, since this ticket is now the top Google hit for "spork DRb::DRbConnError". :)

**Comment by rdp** [comment]
maybe you should report it to that gem?

**Comment by indirect** [comment]
I tweeted at the author, and he replied ["then drb is broken."](https://twitter.com/jamesgolick/status/137817762587353088).

**Comment by coryschires** [comment]
I'm also using `always_verify_ssl_certificates` and can confirm that removing it from my gemfile fixed the problem for me as well. However, I need `always_verify_ssl_certificates` in my project so I wouldn't exactly call the issue resolved, at least for me.

Here's how I got them to work together:
1. Remove `always_verify_ssl_certificates` from your `Gemfile`
2. Copy [always_verify_ssl_certificates.rb](https://raw.github.com/jamesgolick/always_verify_ssl_certificates/master/lib/always_verify_ssl_certificates.rb) into your project's `lib` directory
3. Run your tests normally to ensure everything still works properly.
4. Fire up your `spork` server and your tests should run in the background without issue.

This works because you're now requiring `always_verify_ssl_certificates` later in the boot order, which resolves whatever issue exists between `spork` and `always_verify_ssl_certificates`. That said, this is a little hacky. A better solution would require finding the root of the conflict (which I believe could be in either `spork` or `always_verify_ssl_certificates`) and fixing the issue there. But I'm not really keen on digging into these gems especially given the nastiness of that monkey patch and the author's unhelpful response.

Still, I definitely don't like having to copy `always_verify_ssl_certificates.rb` into my project. But it's a small price to pay for faster tests. If anyone discovers something better, please let me know.

PS: @indirect, you're my hero. I'd given up on this issue and resigned myself to slower tests. I'll glad someone had the wherewithal to dig into this issue.

**Comment by indirect** [comment]
@coryschires, I think this episode really underscores the need for a fix to ruby that allows us to verify SSL certificates without doing crazy monkeypatching of Net::HTTP. You could always try that, if you're looking for something to do. ;)

**Comment by unclaimedbaggage** [comment]
+1 re: always_verify_ssl_certificates.

**Comment by felipecsl** [comment]
I'm having this issue and I don't have `always_verify_ssl_certificates` in my Gemfile. There is something else that causes this issue as well :(

**Comment by felipecsl** [comment]
Apparently there is an issue with [Resolv](http://www.ruby-doc.org/stdlib-1.9.3/libdoc/resolv/rdoc/Resolv.html) as well. Disabling it fixed our issue

**Comment by j15e** [comment]
I also experience this very specific issue, only with Ruby 1.9.3 (1.9.2 is working).

I am not using  `always_verify_ssl_certificates`.

I have try almost every spork version, issue is always the same with 1.9.3.

@felipecsl how did you disabled Resolv? I think that might be me issue too as it is a standard library and that my issue occurs only with 1.9.3

**Comment by felipecsl** [comment]
@j15e we just did something similar to this:

``` ruby
unless Rails.env.test?
  require 'resolv'
end
```

**Comment by j15e** [comment]
Ok thanks I see, but my app is not using `resolv` directly, I have no require of this lib in my code. Maybe is it one my gems, I'll try picking them out one by one..

**Comment by felipecsl** [comment]
Yeah if it is not included directly by your code, you'll have to figure out which module/gem included it :(

**Comment by j15e** [comment]
Problematic gem was `net-ping` and I made a patch

https://github.com/hooktstudios/net-ping/tree/spork-1.9.3-patch

I think a gem monkey-pathching std libs is not the very best idea eheh!

**Comment by rdp** [comment]
is resolv-replace the culprit?

**Comment by j15e** [comment]
@rdp from my understanding & the patch I made on net-ping, yes, that was the culprit.

**Comment by alan-andrade** [comment]
I used @j15e fix with net-ping patch. IT worked!!! Cool man.

**Comment by kinkou** [comment]
Just ran into the same issue, but the background seems to be different. Simple `raise` (without any arguments) in my code causes this error:

```
Failure/Error: Unable to find matching line from backtrace
DRb::DRbConnError: druby://127.0.0.1:8989 - #<Errno::ECONNREFUSED: Connection refused - connect(2)>
# -e:1:in `<main>'
```

**Comment by revathskumar** [comment]
I had the same issue when I run minitest with guard. But solved it running `spork` seperately in another terminal. 

Ruby: 2.0.0-p353
Rails: 4.0.0

```
# Gemfile.lock
    spork (1.0.0rc4)
    spork-minitest (0.0.3)
      spork
    spork-rails (4.0.0)
      rails (>= 3.0.0, < 5)
      spork (>= 1.0rc0)

    guard (1.8.3)
      formatador (>= 0.2.4)
      listen (~> 1.3)
      lumberjack (>= 1.0.2)
      pry (>= 0.9.10)
      thor (>= 0.14.6)
    guard-coffeescript (1.3.4)
      coffee-script (>= 2.2.0)
      guard (>= 1.1.0)
    guard-livereload (1.4.0)
      em-websocket (>= 0.5.0)
      guard (>= 1.8.0)
      multi_json (~> 1.7)
    guard-minitest (1.3.1)
      guard (>= 1.8)
      minitest (>= 2.1)
```
