### ISSUE TITLE
ruby-debug is not listed as a gem dependency but it fails without it

### ISSUE THREAD

**Issue by bmabey** [sporkrb/spork#14]
FYI

**Comment by timcharper** [comment]
I could be wrong on this, but it seems that ruby-debug is optional, and it would be better to install a minimum set of dependencies, rather than a maximum set.  What do you think?

**Comment by bmabey** [comment]
IIRC if you don't have ruby-debug installed it raises an exception when spork tries to require 'ruby-debug'.  (Thereby forcing the dependency.)  I agree that it is optional.. so perhaps the require should be wrapped in a begin-rescue block and an warning message issued instead of erroring out?

**Comment by timcharper** [comment]
it only gets loaded if you require 'spork/ext/ruby-debug' in your project, which isn't required by default.

Perhaps a warning message if you require your project is requiring spork/ext/ruby-debug is in order.

Or we could always require ruby-debug in spork.  It's still... experimental.  Lots of monkey patches applied to get it to work.  Would prefer to keep expectations low on it.

**Comment by bmabey** [comment]
Ah, ok.  I didn't realize that.  My mistake!

**Comment by timcharper** [comment]
ok :) closing
