### ISSUE TITLE
Rails 3.1 Depreciation Warning

### ISSUE THREAD

**Issue by mattmartini** [sporkrb/spork#143]
Spork is throwing these errors under Rails 3.1.  Is there a way to fix these?

Matt

NOTE: Gem.latest_load_paths is deprecated with no replacement. It will be removed on or after 2011-10-01.
Gem.latest_load_paths called from $HOME/.rvm/gems/ruby-1.9.2-p180@mymatch/gems/spork-0.8.5/lib/spork.rb:112.
NOTE: Gem.all_partials is deprecated with no replacement. It will be removed on or after 2011-10-01.
Gem.all_partials called from $HOME/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems.rb:603.
NOTE: Gem.all_partials is deprecated with no replacement. It will be removed on or after 2011-10-01.
Gem.all_partials called from $HOME/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems.rb:603.

**Comment by vizjerai** [comment]
This was fixed in spork 0.9.0.rc7
