### ISSUE TITLE
Gem.latest_load_paths is deprecated

### ISSUE THREAD

**Issue by ZhangHanDong** [sporkrb/spork#149]
NOTE: Gem.latest_load_paths is deprecated with no replacement. It will be removed on or after 2011-10-01.
Gem.latest_load_paths called from /Users/iclick/.rvm/gems/ruby-1.9.2-p290/gems/spork-0.8.5/lib/spork.rb:112.

**Comment by nofxx** [comment]
It's fixed. Use gem install spork --prerelease, add '0.9.0.rc9' to your Gemfile.
Or just wait, heh ;)

**Comment by ZhangHanDong** [comment]
thanks.
