### ISSUE TITLE
rspec not honoring tags (like :focus) when run in spork 

### ISSUE THREAD

**Issue by skaufman** [sporkrb/spork#166]
Discussed more fully here:

http://groups.google.com/group/rubyonrails-talk/browse_thread/thread/a13fc86501c68a34?hl=en

When there are specs with examples tagged :focus => true, the following behavior is seen:
- rspec run alone recognizes the tag and limits the tests to the tagged examples
- rspec run within spork ignores the tag and runs all examples

This appears to be due to some new incompatibility between spork and rspec due to the recent update of rspec to 2.8.x.

**Comment by jfelchner** [comment]
I'm not sure here @thibaudgg, @timcharper everything works fine _except_ when running through guard with Spork.

```
rspec my_spec.rb # including a filtered spec
```

^^^ Works

```
guard
Guard::RSpec is running, with RSpec 2!
Running: my_spec.rb
```

^^^ Works

```
guard
Starting Spork for RSpec
Using RSpec
Preloading Rails environment
Loading Spork.prefork block...
Spork is ready and listening on 8989!
Spork server for RSpec successfully started
Guard::RSpec is running, with RSpec 2!
Running: my_spec.rb
```

^^^ Does not work

Simply running the spec with only Spork running (no guard) also does not work.

I include a lot of files in the prefork block in spec_helper.

This file behaves as it should:

```
RSpec.configure do |config|
  # Configure RSpec to respect the alias 'pit' for pending specs
  config.alias_example_to :pit, :pending => true
end
```

This file does not:

```
RSpec.configure do |config|
  # Configure RSpec to run focused specs, and also respect the alias 'fit' for focused specs
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.filter_run       :focused => true
  config.alias_example_to :fit, :focused => true
  config.run_all_when_everything_filtered = true
end
```

All of this was working perfectly fine before the RSpec 2.8 upgrade.

**Comment by SegFaultAX** [comment]
I'm seeing the exact behavior as above, except I'm using it to disable certain specs rather than focus execution via `config.filter_run_excluding :disabled => true`. Again, it only became an issue with the 2.8 update.

**Comment by thibaudgg** [comment]
I think it's a issue with RSpec 2.8, have you try to add `--tag disabled` in your `.rspec` file?

**Comment by raston** [comment]
I'm seeing this same problem since upgrading to RSpec 2.8. Adding `--tag focus` to `.rspec` is a good workaround and fixes the problem for now.

**Comment by skaufman** [comment]
`--tag focus` added to `.rspec` indeed fixes this! Hurrah!

Since the problem turned out to be with rspec -- not spork -- after all, I'll close this issue here.

**Comment by jfelchner** [comment]
@skaufman can you leave this issue open until we hear from @timcharper or @dchelimsky on this?  The fact that RSpec works correctly EXCEPT when Spork is running makes me think that it is a Spork issue, but I don't know enough about Spork OR RSpec to be sure.

@thibaudgg this is a decent workaround for now but even though it's the case that `--tag focus` to the `.rspec` file might "work", in my opinion, it is not the solution.  For one, the `.rspec` file is a per-developer configuration and should not be checked into version control.  Whereas a project-wide configuration should be.

**Comment by thibaudgg** [comment]
@jfelchner I agree, this is only a temporary workaround.

**Comment by skaufman** [comment]
@dchelimsky is on the case: https://github.com/rspec/rspec-core/issues/554

**Comment by jmuheim** [comment]
This seems to be still necessary (adding `--tag focus` to `.rspec`). Is there any update on this issue?

**Comment by jfelchner** [comment]
@skaufman can we go ahead and close this out please?

**Comment by skaufman** [comment]
Closed. Forget about this entirely. Sorry.
