### ISSUE TITLE
Custom helper aren't found when running spork

### ISSUE THREAD

**Issue by JerryWho** [sporkrb/spork#17]
If I use a custom helper method in a view spork generates an error because this helper method is unknown. If the method is in a controller helper (app/helpers/items_helper.rb in my example) everything is okay.

I put an example on github: http://github.com/JerryWho/test
If rake spec is run without spork all tests pass. But with spork an error occurs:

ActionView::TemplateError in '/items/index.html.erb renders a list of items'
undefined method `simpleFunction' for #ActionView::Base:0x243ca54

In tmp/rails-debug.log I write the loaded files. app/helpers/simple_helper.rb appears. app/helpers/items_helper.rb also appears.

**Comment by timcharper** [comment]
Just to help me, this is an issue from this thread:

http://groups.google.com/group/sporkgem/browse_thread/thread/631f143d2c10277d

**Comment by JerryWho** [comment]
Yeah, that's the right thread. You don't give me much hope in your answer there ;-)
But I often use custom helpers so I stumbled across this problem with my first rails app I wanted to use with spork.

**Comment by timcharper** [comment]
this was fixed
