### ISSUE TITLE
 warning: already initialized constant SUPPORTED_FRAMEWORKS

### ISSUE THREAD

**Issue by cswilliams** [sporkrb/spork#18]
after upgrading from 0.7.3 to 0.7.4, I now get the following warning when I start up the spork server:
/Library/Ruby/Gems/1.8/gems/spork-0.7.4/bin/../lib/spork/app_framework.rb:8: warning: already initialized constant SUPPORTED_FRAMEWORKS

Doesn't seem to affect anything though.

**Comment by emilford** [comment]
I'm getting the same error after upgrading.

**Comment by timcharper** [comment]
is it an error, or is it just a warning?

**Comment by cswilliams** [comment]
it's just a warning, doesn't seem to have any side effects either

**Comment by timcharper** [comment]
.
