### ISSUE TITLE
Reloading Models with inherited hooks

### ISSUE THREAD

**Issue by johnkchow** [sporkrb/spork#194]
I'm running into a problem with the reload of my model classes with the `.inherited` hook.

I have a base model `Game`, and when it's inherited I want to store its subclasses:

``` ruby
class Game
  def self.inherited(klass)
    @subclasses ||= {}
    @subclasses[klass.codename] = klass
  end

  def self.get_subclass(codename)
    @subclasses[codename]
  end
end

class SimpleGame < Game
  def self.codename
    'somesimplecodename'
  end
end
```

This works when I'm running Rails/console, but not Spork. I've tried running `ActiveSupport::Dependencies.clear` in the `.each_run` and `.prefork` hooks, but doesn't seem to be working. Any ideas?

**Comment by thedarkone** [comment]
Shooting in the dark: have you tried using `ActiveSupport::DescendantsTracker`?

**Comment by johnkchow** [comment]
After looking at the code, I'm gonna give that a shot @thedarkone. Looks like the `ActiveSupport::Dependencies.clear` should also reset the inheritance. Appreciate the tip.
