### ISSUE TITLE
spec_helper example

### ISSUE THREAD

**Issue by thibaudgg** [sporkrb/spork#2]
It'll be great to have an idea of what you put inside Spork.prefork and Spork.each_run blocks in your spec_helper.rb, can you give an example, please? Thanks!

**Comment by deedubs** [comment]
One example for each_run is on the writeup.  RE: problems with mysql connection.

Spork.each_run do
    ActiveRecord::Base.establish_connection # make sure that the db connection is ready.
  end

**Comment by thibaudgg** [comment]
Yes, I have seen that. But it'll be good to have a detailled example with what we must add inside Spork.prefork block. Because when I add

```
ENV["RAILS_ENV"] = "test"
require File.expand_path(File.dirname(__FILE__) + "/../config/environment") unless defined?(RAILS_ROOT)
```

My models aren't reloaded after modification, it's normal?

**Comment by deedubs** [comment]
Yes that would be normal.

Since Spork is forked every time the spec is run it forks the main process, anything set in the prefork method will be for all the processes that fork off the main spork.  So loading your models then will only load them once when spork is initially loaded. And every spec run will use the same models.

**Comment by thibaudgg** [comment]
Ok, I begin to understand :-), so I need to add all the gems I use in the prefork, like

```
Spork.prefork do
  require 'actionmailer'
  require 'actionpack'
  require 'activerecord'
  require 'activeresource'
  require 'activesupport'
  require 'activerecord'
  require 'authlogic'
  ....
```

   end

or there's a better way? Thanks for your help!

**Comment by deedubs** [comment]
I don't know of a better way to pre-load all your gems than what you have there.  If I, or you find one yourself, please post it on this thread to let everyone know!

**Comment by thibaudgg** [comment]
Ok, thanks, I'll do this if I found a better way!

**Comment by timcharper** [comment]
Hi there,

I don't know why I wasn't being notified of this issue, and the thread :S

You don't have to require the gems like that.  You can use your environment.rb.  The latest version of Spork, by default, plays as well as it can with rails, and causes your routes, applicationcontroller, and models to load after the prefork.

Take a look at this feature here for an example of rspec:

http://github.com/timcharper/spork/blob/7e72d5f6da43d0330a2000dc36a1356628e5b08a/features/rails_integration.feature

and here for cucumber:

http://github.com/timcharper/spork/blob/7e72d5f6da43d0330a2000dc36a1356628e5b08a/features/cucumber_rails_integration.feature

Thanks for trying Spork, please post any troubles or frustrations you have with it. I'm anxious to find out how it's working in the real world.

Tim

**Comment by timcharper** [comment]
better yet, see here:

http://wiki.github.com/timcharper/spork/examples

:)

**Comment by thibaudgg** [comment]
Ok, now it's realllllly rocks! Thanks so much Tim!

**Comment by timcharper** [comment]
Just noticed my install instructions were out-dated. remove timcharper-spork and [sudo] gem install spork.

You're welcome!
