### ISSUE TITLE
problems using haml with spork

### ISSUE THREAD

**Issue by cswilliams** [sporkrb/spork#20]
does anyone out there use haml with spork?
we recently converted our project to use haml and now when we run tests with spork, every test fails with something like the following:

```
ActionView::TemplateError: You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.<<
On line #67 of app/views/layouts/application.html.haml

    64:   
    65:     #search_wrap{:class => %Q!#{controller.controller_name}_#{controller.action_name}!}
    66:       .container
    67:         - form_tag({:controller => 'products', :action => 'search', :protocol => 'http://', :only_path => false}, {:method => 'get', :id => 'sform'}) do
    68:           %h2
    69:             %label{:for => 'search_field', :title => 'Find'} Find:
```

It seems that anywhere we use form_tag in our views we get that error, doesn't seem to matter what is in form_tag either. It will throw the error with no parameters as well.  

Any help would be appreciated.

Thanks!
Chris

**Comment by timcharper** [comment]
this is extremely unfortunate. Is there any additional trace available? I am betting that it is throwing an error somewhere deep within the Haml library.

**Comment by cswilliams** [comment]
sure, here's the backtrace:
method _run_haml_app47views47layouts47application46html46haml in application.html.haml at line 67
method process in haml (2.2.16) rails//lib/sass/plugin/rails.rb at line 19
method test_view in orders_controller_test.rb at line 3080
method run in testsuite.rb at line 38
method each in testsuite.rb at line 37
method run in testsuite.rb at line 37
method run in testsuite.rb at line 38
method each in testsuite.rb at line 37
method run in testsuite.rb at line 37
method run_suite in testrunnermediator.rb at line 48
method start_mediator in testrunner.rb at line 74
method start in testrunner.rb at line 46
method run in testrunnerutilities.rb at line 24
method run in autorunner.rb at line 269
method run_tests in test_unit.rb at line 10
method run in spork (0.7.3) bin//lib/spork/run_strategy/forking.rb at line 13
method initialize in spork (0.7.3) bin//lib/spork/forker.rb at line 20
method fork in spork (0.7.3) bin//lib/spork/forker.rb at line 18
method initialize in spork (0.7.3) bin//lib/spork/forker.rb at line 18
method new in spork (0.7.3) bin//lib/spork/run_strategy/forking.rb at line 9
method run in spork (0.7.3) bin//lib/spork/run_strategy/forking.rb at line 9
method run in spork (0.7.3) bin//lib/spork/server.rb at line 46
method __send__ in drb.rb at line 1562
method perform_without_block in drb.rb at line 1562
method perform in drb.rb at line 1522
method main_loop in drb.rb at line 1596
method loop in drb.rb at line 1592
method main_loop in drb.rb at line 1592
method start in drb.rb at line 1588
method main_loop in drb.rb at line 1588
method run in drb.rb at line 1437
method start in drb.rb at line 1434
method run in drb.rb at line 1434
method initialize in drb.rb at line 1354
method new in drb.rb at line 1634
method start_service in drb.rb at line 1634
method listen in spork (0.7.3) bin//lib/spork/server.rb at line 28
method run in spork (0.7.3) bin//lib/spork/server.rb at line 20
method run in spork (0.7.3) bin//lib/spork/runner.rb at line 77
method run in spork (0.7.3) bin//lib/spork/runner.rb at line 12
at top level in spork (0.7.3) bin/spork at line 10
method load in spork at line 19
at top level in spork at line 19

**Comment by timcharper** [comment]
Sorry... closing for staleness. I just never got to it. Please re-open if still a problem with later versions of haml
