### ISSUE TITLE
Nested models and RSpec

### ISSUE THREAD

**Issue by jweir** [sporkrb/spork#22]
Hello,

Spork is not reloading nested models which change.

For example

```
 app/models/customer.rb
 app/models/customer/subscriptions.rb
```

Both are loaded fine, but any changes to the files are not reflected.  Is there work around?  If not I can put together a sample demonstrating the issue.

My spec_helper.rb http://gist.github.com/286048

spork (0.7.5)
rspec (1.3.0)
rspec-rails (1.3.2)

Thanks - JW

**Comment by jweir** [comment]
sorry, this issue was somehow double posted

**Comment by timcharper** [comment]
where is the duplicate issue?

**Comment by timcharper** [comment]
Nevermind :-) I found the duplicate
