### ISSUE TITLE
Rails 4 support

### ISSUE THREAD

**Issue by thehappycoder** [sporkrb/spork#223]
Spork is not working with rails4

Missing or uninitialized constant: ActiveModel::Observing (NameError)
kernel/common/module.rb:439:in `const_missing'
/Users/anton/.rvm/gems/rbx-2.0.0-rc1/gems/spork-0.9.2/lib/spork/app_framework/rails.rb:56:in`preload_rails'
/Users/anton/.rvm/gems/rbx-2.0.0-rc1/gems/spork-0.9.2/lib/spork/app_framework/rails.rb:7:in `preload'
/Users/anton/.rvm/gems/rbx-2.0.0-rc1/gems/spork-0.9.2/lib/spork/test_framework.rb:134:in`preload'
/Users/anton/.rvm/gems/rbx-2.0.0-rc1/gems/spork-0.9.2/lib/spork.rb:62:in `exec_prefork'
/Users/anton/.rvm/gems/rbx-2.0.0-rc1/gems/spork-0.9.2/lib/spork/test_framework.rb:120:in`preload'
/Users/anton/.rvm/gems/rbx-2.0.0-rc1/gems/spork-0.9.2/lib/spork/run_strategy/forking.rb:25:in `preload'
/Users/anton/.rvm/gems/rbx-2.0.0-rc1/gems/spork-0.9.2/lib/spork/runner.rb:74:in`run'
/Users/anton/.rvm/gems/rbx-2.0.0-rc1/gems/spork-0.9.2/lib/spork/runner.rb:10:in `run'
/Users/anton/.rvm/gems/rbx-2.0.0-rc1/gems/spork-0.9.2/bin/spork:10:in`**script**'
kernel/common/kernel.rb:598:in `load'
/Users/anton/.rvm/gems/rbx-2.0.0-rc1/bin/spork:19:in`**script**'
kernel/common/block_environment.rb:75:in `call_on_instance'
kernel/common/eval.rb:75:in`eval'
/Users/anton/.rvm/gems/rbx-2.0.0-rc1/bin/ruby_noexec_wrapper:14:in `__script__'
kernel/delta/codeloader.rb:68:in`load_script'
kernel/delta/codeloader.rb:118:in `load_script'
kernel/loader.rb:615:in`script'
kernel/loader.rb:816:in `main'

Even adding this to Gemfile doesn't help
gem 'rails-observers'

**Comment by batasrki** [comment]
Until this gets fixed, you can do the following:

``` zsh
  gem install gemedit
  gem edit spork
```

In **lib/spork/app_framework/rails.rb**, on line **56**, comment out the following

``` ruby
  Spork.trap_method(::ActiveModel::Observing::ClassMethods, :instantiate_observers)
```

That'll make it work again. I don't want to make that a PR, as I don't know what behaviour will be broken.

**Comment by akshayrawat** [comment]
+1

**Comment by thehappycoder** [comment]
It is working fine so far.

**Comment by ewollesen** [comment]
A potentially simpler fix is to add this line before requiring spork (eg before `require 'spork' in your`spec_helper.rb`):

``` ruby
module ActiveModel; module Observing; end; end # Prevents spork from exiting due to non-existent class in rails4.
```

**Comment by macfanatic** [comment]
I am on Rails 4 without ActiveRecord and get the same error. Using @ewollesen's suggestion does not work.

**Comment by macfanatic** [comment]
Anyone even know if this is actively maintained? Last commit was 6 months ago & the homepage link on rubygems.org takes you to a repo that doesn't exist...

**Comment by ewollesen** [comment]
The original author works next door. He's not abandoned it, his attention is just mostly elsewhere.

**Comment by ewollesen** [comment]
This might also be of use:

https://github.com/sporkrb/spork-rails/pull/16

**Comment by ivawzh** [comment]
+1

**Comment by phildionne** [comment]
+1

**Comment by bking39116** [comment]
+1

**Comment by adamcrown** [comment]
+1

**Comment by cschiewek** [comment]
:+1:

**Comment by miclovich** [comment]
:+1:

**Comment by sahilm** [comment]
Support for Rails 4, Ruby 2.0, Cucumber 1.3.2 and Rspec 2.13.0 has landed on master. Please help me test by including `spork-rails, :github => 'sporkrb/spork-rails'` in your Gemfile.

CI builds for spork and spork-rails have been setup at https://travis-ci.org/sporkrb/spork and https://travis-ci.org/sporkrb/spork-rails respectively.

**Comment by miclovich** [comment]
@sahilm this works well on mine; thanks.

**Comment by nacengineer** [comment]
@sahilm this fixes the issue for me too! :) thanks

**Comment by randoum** [comment]
@sahilm it works for me too, thanks

**Comment by ghost** [comment]
Worked here too.

**Comment by ckgagan** [comment]
Works for me too hurray :)

**Comment by aweis89** [comment]
+1, as in worked for me

**Comment by kyletolle** [comment]
@sahilm this worked for me too. Thanks!

**Comment by jamesw** [comment]
spork-rails, :github => 'sporkrb/spork-rails' is working great for me. Thank you

**Comment by organicweb** [comment]
@sahilm Works for me too, thank you

**Comment by sciurus** [comment]
I see this was fixed in July 2013, but the last spork release was in May 2012. Any chance of a new release with these fixes, so people can install from Rubygems rather than GIthub??

**Comment by dougiebuckets** [comment]
+1

**Comment by carstengehling** [comment]
@sahilm It works perfectly

For those who run into dependency issues: Your spork gem also needs to be loaded from master. Use this in your Gemfile:

```
gem 'spork', :github => 'sporkrb/spork'
gem 'spork-rails', :github => 'sporkrb/spork-rails'
```

**Comment by sahilm** [comment]
I've released new versions of spork and spork-rails. There's no need to install from GitHub anymore.

**Comment by sameera207** [comment]
@sahilm , thanks mate.. :+1:  , your solution worked... 

Im on rails 4.0.1, ruby 2.0

**Comment by phuong3030** [comment]
@sahilm, thank you.

**Comment by railsfactory-kumaresan** [comment]
@sahilm, Great it works fine in Rails 4.1.0.

**Comment by AshMcConnell** [comment]
@sahilm I still have this error "NameError: uninitialized constant ActiveModel::Observing" when using the github master and jruby-1.7.19 / Rails 4.2.  Is there any workaround?

Thanks!

**Comment by watsy0007** [comment]
@carstengehling thx,it work for me.

**Comment by chevinbrown** [comment]
Awesome! +1
