### ISSUE TITLE
Spork closes down when spec throw an exception

### ISSUE THREAD

**Issue by fox** [sporkrb/spork#23]
As the title says, each time spec command throws some kind of exception, spork will close down.

For example, trying to run something like:

spec non_existent_file.rb

throws the expected 'file not found' error, and in the spork window I get:

<code>
Spork is ready and listening on 8989!
/var/lib/gems/1.8/gems/spork-0.7.5/bin/../lib/spork/forker.rb:42:in `load': end of file reached (EOFError)
    from /var/lib/gems/1.8/gems/spork-0.7.5/bin/../lib/spork/forker.rb:42:in`result'
    from /var/lib/gems/1.8/gems/spork-0.7.5/bin/../lib/spork/forker.rb:40:in `initialize'
    from /var/lib/gems/1.8/gems/spork-0.7.5/bin/../lib/spork/forker.rb:40:in`new'
    from /var/lib/gems/1.8/gems/spork-0.7.5/bin/../lib/spork/forker.rb:40:in `result'
    from /var/lib/gems/1.8/gems/spork-0.7.5/lib/spork/run_strategy/forking.rb:15:in`run'
</code>
I'm using:

spork (0.7.5)
rspec (1.3.0)
rspec-rails (1.3.2)
rails (2.3.5)

**Comment by timcharper** [comment]
resolved
