### ISSUE TITLE
breaks when used with test_notifer

### ISSUE THREAD

**Issue by drewB** [sporkrb/spork#25]
There is a wonderful gem call test_notifer (http://github.com/fnando/
test_notifier) that gives you desktop notifications of the results
when your tests complete (so you don't have to look at the
terminal).

Unfortunately, spork and test_notifer don't seem to play nice together
when running rspec (I haven't tried it with other frameworks).  If you
require test_notifer/rspec in spec helper everything works great when
spork isn't running but if you try to run spork you get the follow
errors:

undefined method `map' for nil:NilClass (NoMethodError)
/usr/local/lib/site_ruby/1.8/rubygems.rb:270:in`activate'
/usr/local/lib/site_ruby/1.8/rubygems.rb:296:in `activate'
/usr/local/lib/site_ruby/1.8/rubygems.rb:295:in`each'
/usr/local/lib/site_ruby/1.8/rubygems.rb:295:in `activate'
/usr/local/lib/site_ruby/1.8/rubygems.rb:296:in`activate'
/usr/local/lib/site_ruby/1.8/rubygems.rb:295:in `each'
/usr/local/lib/site_ruby/1.8/rubygems.rb:295:in`activate'
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:35:in
`require'
/path_to_rails_app/spec/spec_helper.rb:4
/usr/lib/ruby/gems/1.8/gems/spork-0.7.5/lib/spork/test_framework.rb:
138:in`load'
/usr/lib/ruby/gems/1.8/gems/spork-0.7.5/lib/spork/test_framework.rb:
138:in `preload'
/usr/lib/ruby/gems/1.8/gems/spork-0.7.5/lib/spork/app_framework/
rails.rb:121:in`preload'
/usr/lib/ruby/gems/1.8/gems/spork-0.7.5/lib/spork/test_framework.rb:
134:in `preload'
/usr/lib/ruby/gems/1.8/gems/spork-0.7.5/bin/../lib/spork.rb:57:in
`exec_prefork'
/usr/lib/ruby/gems/1.8/gems/spork-0.7.5/lib/spork/test_framework.rb:
120:in `preload'
/usr/lib/ruby/gems/1.8/gems/spork-0.7.5/lib/spork/run_strategy/
forking.rb:23:in`preload'
/usr/lib/ruby/gems/1.8/gems/spork-0.7.5/bin/../lib/spork/runner.rb:
74:in `run'
/usr/lib/ruby/gems/1.8/gems/spork-0.7.5/bin/../lib/spork/runner.rb:
9:in`run'
/usr/lib/ruby/gems/1.8/gems/spork-0.7.5/bin/spork:10
/usr/bin/spork:19:in `load'
/usr/bin/spork:19

**Comment by timcharper** [comment]
Bummer.  I saw your email to the list, this is a better place for it.

I take it /path_to_rails_app/spec/spec_helper.rb:4 is where test_notifier is loaded ?

**Comment by drewB** [comment]
correct

**Comment by drewB** [comment]
I should also say that a similar error occurs when running without spork if test_notifier is loaded after config/environment.

**Comment by timcharper** [comment]
Can you post a sample project that replicates the problem?

**Comment by timcharper** [comment]
(what I would do is use Ruby-debug to trace in and find the exact point of failure)

**Comment by drewB** [comment]
I am having difficult replicating it outside of my current project.  If I am able to, I will post a sample project.

**Comment by timcharper** [comment]
not easily reproduced, bummer. Closing for now.
