### ISSUE TITLE
Application Controller not loading for Windows

### ISSUE THREAD

**Issue by cbaclig** [sporkrb/spork#26]
I'm actually using the milhouse-spork gem, but it looks like that's been merge back in with the main branch so I'll post this here.

When running my specs with spork, my ApplicationController wasn't being loaded properly.  After digging around expanded_caller in lib/spork.rb wasn't parsing caller line's properly because on Windows, the line include the disk name where the file lives (i.e. C:/foo/bar.rb:13:something else...) and it looks like the code assumes only the colons around the line number.  

As a quick fix I just changed the split to split on a different regex.  I only have a windows machine to test on, but I think this should keep *nix machines happy too.

And here's a diff: http://gist.github.com/325480

**Comment by timcharper** [comment]
wow, good find! I will get this applied immediately.

**Comment by Milhouse** [comment]
FYI, I'd forgotten that another fork had a commit to fix this issue for 1.8.7: http://github.com/pietervisser/spork/commit/c0c0f2b7ccaeb2dcfcd277aa736d87e63621a04b

**Comment by timcharper** [comment]
Awesome. Which solution do you like better?

**Comment by Milhouse** [comment]
Honestly, I didn't examine them that closely. I'll take a closer look later.

**Comment by Milhouse** [comment]
Since both ways work, I'd stick with the shorter one. BTW, cbaclig, thanks. I noticed the same problem when running a test in The Rspec Book in 25.2 when testing an Application controller to handle an error, but hadn't traced it back to the source.

**Comment by timcharper** [comment]
Agreed

**Comment by timcharper** [comment]
(thank you for looking at them :-))

And cbaclig, again, thank you for the patch.

**Comment by cbaclig** [comment]
No problem.  I should be the one thanking you guys for the work you've done so far!
