### ISSUE TITLE
RSpec 2 support

### ISSUE THREAD

**Issue by ashmoran** [sporkrb/spork#27]
I'm currently trying to get RSpec 2 and Spork working together.  RSpec 2 currently lacks support for DRb, so that must be sorted first, which I'm working on: http://github.com/rspec/rspec-core/issues/issue/2

However, the architecture of RSpec 2 has changed in a way that makes the current interface to RSpec inappropriate.  (Extract below.)

```
def run_tests(argv, stderr, stdout)
  ::Spec::Runner::CommandLine.run(
    ::Spec::Runner::OptionParser.parse(
      argv,
      stderr,
      stdout
    )
  )
end
```

I could implement `::Spec::Runner::CommandLine` etc as an adapter in RSpec 2, but that would be a kludge.

I noticed that the `TestFramework` hierarchy is OCP-conformant, but with two limitations: it's only conformant with respect to helper file detection, and you can't (AFAICT) get Spork to load `TestFramework` subclasses from other gems before it runs the detection code.  (If the second situation was possible, I could implement the `Spork::TestFramework::RSpec2` inside RSpec 2 itself without forking Spork.)

My plan is to extend open the hierarchy to allow detection based secondarily on helper file contents, as you can figure out which version of RSpec is in use based on require lines (`require 'spec'` vs `require 'rspec/core'`).

I still need to figure out the most correct interface to expose in RSpec 2 for the new adapter to communicate with - so I'll possibly invalidate some of this discussion, but I though I'd put this up as a brain dump.

Let me know if you have any thoughts! Cheers - Ash

**Comment by ashmoran** [comment]
BTW my branch is in an intermediate state, as I was trying to port Spork's features to use Aruba.  Next step is to try Aslak's forking_children Aruba branch.

**Comment by timcharper** [comment]
Great on porting the features to Aruba! But as for the debugger features, I think the two-way communication is needed.  I think we'll need Popen3 at the very least.

I think it would be best to implement Spork::TestFramework::RSpec2 inside of RSpec.  I'm surprised that you're finding that Spork does the framework detection _before_ checking loading TestFramework subclasses from other gems.  We'll have to check into that.

As for being limited to helper file detection only... one can just override self.available? to change this behavior.

**Comment by timcharper** [comment]
Getting closer on Rspec 2.0 on my side.  I've got a rails 3 branch in the works, and am working towards getting it working.

**Comment by ashmoran** [comment]
Cool!  I don't have time to work on it unfortunately but let me know if you have any questions.

**Comment by timcharper** [comment]
fair enough, it's taken me forever to get motivated enough to work on it.  I knew it was going to sink a score of hours.

In my rails3 branch, I'm getting an issue that seems to be on the rspec side.  Here's the output:

```
expected "Exception encountered: #<NoMethodError: undefined method `configure' for [\"spec/did_it_work_spec.rb\"]:Array>
backtrace:
/Users/timcharper/.rvm/gems/ruby-1.8.7-p249/gems/rspec-core-2.0.0.beta.16/lib/rspec/core/command_line.rb:11:in `run'
/Users/timcharper/.rvm/gems/ruby-1.8.7-p249/gems/rspec-core-2.0.0.beta.16/lib/rspec/monkey/spork/test_framework/rspec.rb:4:in `run_tests'
/Users/timcharper/projects/spork/lib/spork/run_strategy/forking.rb:13:in `run'
/Users/timcharper/projects/spork/lib/spork/forker.rb:21:in `initialize'
/Users/timcharper/projects/spork/lib/spork/forker.rb:18:in `fork'
/Users/timcharper/projects/spork/lib/spork/forker.rb:18:in `initialize'
/Users/timcharper/projects/spork/lib/spork/run_strategy/forking.rb:9:in `new'
/Users/timcharper/projects/spork/lib/spork/run_strategy/forking.rb:9:in `run'
/Users/timcharper/projects/spork/lib/spork/server.rb:47:in `run'
/Users/timcharper/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/drb/drb.rb:1558:in `__send__'
/Users/timcharper/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/drb/drb.rb:1558:in `perform_without_block'
/Users/timcharper/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/drb/drb.rb:1518:in `perform'
/Users/timcharper/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/drb/drb.rb:1592:in `main_loop'
/Users/timcharper/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/drb/drb.rb:1588:in `loop'
/Users/timcharper/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/drb/drb.rb:1588:in `main_loop'
/Users/timcharper/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/drb/drb.rb:1584:in `start'
/Users/timcharper/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/drb/drb.rb:1584:in `main_loop'
/Users/timcharper/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/drb/drb.rb:1433:in `run'
/Users/timcharper/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/drb/drb.rb:1430:in `start'
/Users/timcharper/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/drb/drb.rb:1430:in `run'
/Users/timcharper/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/drb/drb.rb:1350:in `initialize'
/Users/timcharper/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/drb/drb.rb:1630:in `new'
/Users/timcharper/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/drb/drb.rb:1630:in `start_service'
/Users/timcharper/projects/spork/lib/spork/server.rb:29:in `listen'
/Users/timcharper/projects/spork/lib/spork/server.rb:20:in `run'
/Users/timcharper/projects/spork/bin/../lib/spork/runner.rb:76:in `run'
/Users/timcharper/projects/spork/bin/../lib/spork/runner.rb:10:in `run'
/Users/timcharper/projects/spork/bin/spork:10
" to include "Specs successfully run within spork, and all initialization files were loaded" (Spec::Expectations::ExpectationNotMetError)
 ./features/steps/sandbox_steps.rb:94:in `/^the (error output|output) should contain "(.+)"$/'
 features/rspec_rails_integration.feature:65:in `And the output should contain "Specs successfully run within spork, and all initialization files were loaded"'
```

It can be reproduced by checkout out my rails3 branch and running:

```
bundle install
bin/cucumber features/rspec_rails_integration.feature:35
```

That will show the error and generate the project.  One can cd `tmp/sandbox/temp_rails_project` and play with it further.

Any idea what's going on?  Looks like here we initialize the CommandLine object with the provided arguments:

http://github.com/rspec/rspec-core/blob/v2.0.0.beta.16/lib/rspec/monkey/spork/test_framework/rspec.rb#L4

But then, that's eventually becomes "@options", which later has .configure requested from it.

http://github.com/rspec/rspec-core/blob/v2.0.0.beta.16/lib/rspec/core/command_line.rb#L5-11

**Comment by ashmoran** [comment]
I had a conversation with David about the interface, he decided to change it so it passed an object of some sort, not just the args.  Apparently this broke:

http://github.com/rspec/rspec-core/issues/closed#issue/61

However I haven't seen the new code so you might get a better answer from David - he might know what's going on off the top of his head.  Sorry I can't be more help.

**Comment by timcharper** [comment]
it's done. Thanks!
