### ISSUE TITLE
Easy gem dependency installation

### ISSUE THREAD

**Issue by ashmoran** [sporkrb/spork#28]
While doing some work on Spork I noticed that to run all the features (which I'm having trouble with - separate problem though) you have to install a lot of gems.  Something like a rake task, or possibly a Bundler Gemfile would make it quicker to get up and running.  This is also convenient if (like me) you use rvm, and occasionally bomb a gemset if general weirdness occurs.

**Comment by timcharper** [comment]
Geminstaller is alreaydy set up. See geminstaller.yml. :)

Probably should add running tests instructions to the readme. Documentation fail.
Tim

**Comment by ashmoran** [comment]
Hi Tim

I'm gonna sound thick now, but how do I use geminstaller.yml?

Ta
Ash

**Comment by ashmoran** [comment]
BTW any chance you can let me on the mailing list? (Sent an invoice a little while ago.)  I'm having some trouble running the features and I don't know why.

**Comment by timcharper** [comment]
latest master is using gem bundler, for both running specs and for generating rails projects that are tested with cucumber.

**Comment by ashmoran** [comment]
Awesome! I love Bundler :)
