### ISSUE TITLE
Please add some screen activity when the spork is used

### ISSUE THREAD

**Issue by gudata** [sporkrb/spork#29]
Hello,
Please add some screen activity when the spork is used.
How could I be sure if my autotest is using spork?
Maybe there is already such an option which I can enable?

**Comment by rdp** [comment]
+1 (like a dot or something)

**Comment by timcharper** [comment]
show output each time spork is invoked

closed by df208477341f93b38cf72297b242309684e9b2d5

**Comment by timcharper** [comment]
fixed with df208477341f93b38cf72297b242309684e9b2d5

**Comment by gudata** [comment]
thanks!
