### ISSUE TITLE
starting spork causes segfault on Windows under Ruby 1.9.1

### ISSUE THREAD

**Issue by arvicco** [sporkrb/spork#31]
System: Win XP Pro SP3
Ruby: ruby 1.9.1p378 (2010-01-10 revision 26273) [i386-mingw32]
Gems:
rspec (1.3.0)
spork (0.8.1)
win32-api (1.4.6)
win32-process (0.6.2)
## Trace below:

C:\Dev\apps\win\dde>spork
Using RSpec
C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/win32-api-1.4.6-x86-mingw32/lib/win32/api.so: [BUG] Segmentation fault
ruby 1.9.1p378 (2010-01-10 revision 26273) [i386-mingw32]

-- control frame ----------
c:0027 p:-5020060 s:0078 b:0078 l:000077 d:000077 TOP
c:0026 p:---- s:0076 b:0076 l:000075 d:000075 CFUNC  :require
c:0025 p:0011 s:0072 b:0072 l:000071 d:000071 TOP    C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/windows-api-0.4.0/lib/windows/api.rb:1
c:0024 p:---- s:0070 b:0070 l:000069 d:000069 FINISH
c:0023 p:---- s:0068 b:0068 l:000067 d:000067 CFUNC  :require
c:0022 p:0011 s:0064 b:0064 l:000063 d:000063 TOP    C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/windows-pr-1.0.9/lib/windows/error.rb:12
c:0021 p:---- s:0062 b:0062 l:000061 d:000061 FINISH
c:0020 p:---- s:0060 b:0060 l:000059 d:000059 CFUNC  :require
c:0019 p:0011 s:0056 b:0056 l:000055 d:000055 TOP    C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/win32-process-0.6.2/lib/win32/process.rb:1
c:0018 p:---- s:0054 b:0054 l:000053 d:000053 FINISH
c:0017 p:---- s:0052 b:0052 l:000051 d:000051 CFUNC  :require
c:0016 p:0047 s:0048 b:0048 l:000047 d:000047 TOP    C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/spork-0.8.1/lib/spork/run_strategy/magazine.rb:6
c:0015 p:---- s:0046 b:0046 l:000045 d:000045 FINISH
c:0014 p:---- s:0044 b:0044 l:000043 d:000043 CFUNC  :require
c:0013 p:0012 s:0040 b:0040 l:000031 d:000039 BLOCK  C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/spork-0.8.1/lib/spork/run_strategy.rb:44
c:0012 p:---- s:0037 b:0037 l:000036 d:000036 FINISH
c:0011 p:---- s:0035 b:0035 l:000034 d:000034 CFUNC  :each
c:0010 p:0049 s:0032 b:0032 l:000031 d:000031 TOP    C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/spork-0.8.1/lib/spork/run_strategy.rb:44
c:0009 p:---- s:0030 b:0030 l:000029 d:000029 FINISH
c:0008 p:0133 s:0028 b:0028 l:000027 d:000027 METHOD C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/spork-0.8.1/lib/spork/runner.rb:73
c:0007 p:0023 s:0023 b:0023 l:000022 d:000022 METHOD C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/spork-0.8.1/lib/spork/runner.rb:9
c:0006 p:0133 s:0017 b:0017 l:000016 d:000016 TOP    C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/spork-0.8.1/bin/spork:10
c:0005 p:---- s:0013 b:0013 l:000012 d:000012 FINISH
c:0004 p:---- s:0011 b:0011 l:000010 d:000010 CFUNC  :load
c:0003 p:0127 s:0007 b:0007 l:001044 d:001ed8 EVAL   C:/Dev/ruby/bin/spork:19
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
## c:0001 p:0000 s:0002 b:0002 l:001044 d:001044 TOP

-- Ruby level backtrace information-----------------------------------------
C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/windows-api-0.4.0/lib/windows/api.rb:1:in `require'
C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/windows-api-0.4.0/lib/windows/api.rb:1:in`<top (required)>'
C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/windows-pr-1.0.9/lib/windows/error.rb:12:in `require'
C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/windows-pr-1.0.9/lib/windows/error.rb:12:in`<top (required)>'
C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/win32-process-0.6.2/lib/win32/process.rb:1:in `require'
C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/win32-process-0.6.2/lib/win32/process.rb:1:in`<top (required)>'
C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/spork-0.8.1/lib/spork/run_strategy/magazine.rb:6:in `require'
C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/spork-0.8.1/lib/spork/run_strategy/magazine.rb:6:in`<top (required)>'
C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/spork-0.8.1/lib/spork/run_strategy.rb:44:in `require'
C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/spork-0.8.1/lib/spork/run_strategy.rb:44:in`block in <top (required)>'
C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/spork-0.8.1/lib/spork/run_strategy.rb:44:in `each'
C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/spork-0.8.1/lib/spork/run_strategy.rb:44:in`<top (required)>'
C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/spork-0.8.1/lib/spork/runner.rb:73:in `run'
C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/spork-0.8.1/lib/spork/runner.rb:9:in`run'
C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/spork-0.8.1/bin/spork:10:in `<top (required)>'
C:/Dev/ruby/bin/spork:19:in`load'
C:/Dev/ruby/bin/spork:19:in `<main>'

[NOTE]
You may encounter a bug of Ruby interpreter. Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by timcharper** [comment]
Milhouse has recently implemented Ruby 1.9 support for Windows. From what I recall, he never claimed to be for that it did work :-) Milhouse?

**Comment by timcharper** [comment]
I just released milhouse's (Donald Parish's) changes for Ruby 1.9 support for Windows. Try upgrading to sport 0.8.2 and see if it works for you.
