### ISSUE TITLE
Incompatible with role_requirement plugin

### ISSUE THREAD

**Issue by perplexes** [sporkrb/spork#32]
Spork traps EagerPath's load!, which is required to render a 401 page to test role_requirement's ability to lock out people. Has this happened to anyone else? For now I'll monkeypatch..

**Comment by timcharper** [comment]
interesting: I'm not sure why trapping EagerPath.load would cause role requirement to fail. however, this is a valid issue and should be addressed.

**Comment by timcharper** [comment]
What monkey patch ended up working?

**Comment by timcharper** [comment]
.
