### ISSUE TITLE
Rails doesn't recognize that frozen spork has been built

### ISSUE THREAD

**Issue by niels** [sporkrb/spork#34]
Rails determines whether or not a frozen gem (more specifically: it's extensions) has been built by checking for the existance of a Makefile in the extension's directory. Spork however doesn't create one and Rails thus always thinks the frozen gem hasn't been built yet.

I'd suggest to create a dummy Make- instead of Rakefile to remedy this.

**Comment by timcharper** [comment]
can it just be an empty file?

**Comment by timcharper** [comment]
Is this still an issue with the advent of bundler? (thinking not... rails gem dependencies were a mess).

Still, I would have blamed this on rails, not spork.
