### ISSUE TITLE
#<DRb::DRbUnknown:0xb739e290> when asked for Rails.env in Rails3/Rspec2 application

### ISSUE THREAD

**Issue by markiz** [sporkrb/spork#39]
https://gist.github.com/102375ce52b5048e53a2 -- gem list I'm using

App is almost fresh with minimal changes.

**Comment by timcharper** [comment]
Hmm... still happening?  Just released 0.9.0 RC2, but have no idea what would cause this

**Comment by 900feet** [comment]
This is affecting us - rails3/rspec2 using spork

**Comment by 900feet** [comment]
FYI one can do a Rails.env.to_s to get around it, but that's not ideal.
