### ISSUE TITLE
spork 0.8.4 no longer includes Rakefile

### ISSUE THREAD

**Issue by graaff** [sporkrb/spork#41]
This makes it a bit harder then needed to run the specs and features locally. It would be nice to add it back in the next release.

**Comment by timcharper** [comment]
As far as I'm aware, it never did include the rake file. I suppose one could add a rake spork task, but spork has taken the approach of running specs (and features) the same as if you invoked it via the "r{0,1}spec" and "cucumber" command line tools, respectively.

Happy to accept a patch

**Comment by graaff** [comment]
I'm sorry, I thought it was in spork 0.8.3, but I now see it isn't. There is a Rakefile in the repository, though, with targets for specs and cucumber. I guess it makes sense to either remove it or include it in the gem distribution? I'm happy with it either way.
