### ISSUE TITLE
platform-specific bundler Gemfile

### ISSUE THREAD

**Issue by stepheneb** [sporkrb/spork#42]
I wanted to run the test on my rvm installed version of 1.9.2-head and needed to specify that under ruby_19 the gem ruby-debug19 should be installed instead of ruby-debug.

Bundler 1.0 supports specifying platform gem dependencies like this:

```
platforms :ruby_19 do
  gem 'ruby-debug19'
end
platforms :ruby_18 do
  gem 'ruby-debug'
end
```

See comments in this issue for a bit more info: http://github.com/carlhuda/bundler/issues/#issue/426

The 1.0 version is still prerelease so you need to install it like this:

```
gem install bundler --pre
```

Unfortunately ruby-debug19 needs to be passed a path to where the active ruby is:

```
gem install ruby-debug19 -- --with-ruby-include=/Users/stephen/.rvm/src/ruby-1.9.2-head/
```

See this comment: http://github.com/carlhuda/bundler/issues/#issue/23/comment/311834

When I installed ruby-debug19 manually the command 'bundle install' completed successfully.

**Comment by timcharper** [comment]
ok, can you please make this change and send a pull request?  Thanks!

**Comment by stepheneb** [comment]
Just have a minute now so I'll look at this more later ... but in Ruby 1.8.7 (on my Mac) bundle exec rspec spec/ reported: 52 examples, 0 failures but I did get two errors like this displayed on the console:

```
.../lib/spork/run_strategy/magazine/../../../spork/forker.rb:27:in `write': not opened for writing (IOError)
from .../lib/spork/run_strategy/magazine/../../../spork/forker.rb:27:in `puts'
...
```

On Ruby 1.9.2 I started getting many errors:

```
 bundle exec rspec spec/
.....FF etc
```

More details in the console log here: http://gist.github.com/577423

**Comment by timcharper** [comment]
Please open another issue for those problems.
