### ISSUE TITLE
gotcha for the docs: rails3 defaults environment/test.rb to preload models via cache_classes setting

### ISSUE THREAD

**Issue by inspire22** [sporkrb/spork#44]
STUPID!  Rails seems to default to environments/test.rb having:

  config.cache_classes = true

which then causes Rails to "automatically" pre-load all models.  Which causes them to NOT get updated for each spork block.

Thought I'd mention this in case anyone else had this problem.

**Comment by timcharper** [comment]
I've decide that spork 0.9.0 will disable eager loading, regardless of this variable.  I may change my mind if enough people are angry about the decision.

**Comment by inspire22** [comment]
sounds awesome to me!

**Comment by kdaigle** [comment]
I haven't dug into the code, but just for other people who have experienced this issue: it appears that the setting in test.rb does currently take precedence. After upgrading a few Rails 2.3 projects, I was bitten by this. Changing the `cache_classes` setting to `false` seems to have fixed the problem.
