### ISSUE TITLE
Expected spork-0.8.4/lib/spork/app_framework/rails_stub_files/application.rb to define Application

### ISSUE THREAD

**Issue by bryanlarsen** [sporkrb/spork#45]
I get the following error from spork:

```
Expected spork-0.8.4/lib/spork/app_framework/rails_stub_files/application.rb to define Application (LoadError)
```

Yes, I've got a model named Application.  I fixed the problem by deleting the file.  If you ever drop rails 2.2 support, it'd be nice if you did as well.

**Comment by timcharper** [comment]
will be pruned from 0.9.0.  Sorry about the trouble!
