### ISSUE TITLE
[WORKAROUND] Spork won't run [no such file to load -- magazine_slave (LoadError)], ruby 1.9.2, gem 1.3.7, windows

### ISSUE THREAD

**Issue by solymosi** [sporkrb/spork#46]
I could not get Spork to run after a fresh install of Ruby 1.9.2 + gem 1.3.7 on Win7 x64.
The error message was:

<pre><code>Using RSpec
  -- Rinda Ring Server listening for connections...
  -- Starting to fill pool...
     Wait until at least one slave is provided before running tests...
  ** CTRL+BREAK to stop Spork and kill all ruby slave processes **
Spork is ready and listening on 8989!
<internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- magazine_slave (LoadError)
        from <internal:lib/rubygems/custom_require>:29:in `require'
        from magazine_slave_provider.rb:5:in `<main>'
<internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- magazine_slave (LoadError)
        from <internal:lib/rubygems/custom_require>:29:in `require'
        from magazine_slave_provider.rb:5:in `<main>'
</code></pre>

Then found the following workaround:

In lib/spork/run_strategy/magazine/magazine_slave_provider.rb on line 5 change:

<pre><code>require 'magazine_slave'</code></pre>

to:

<pre><code>require './magazine_slave.rb'</code></pre>

I don't call it a patch because I don't think it is an issue related to Spork. It is more likely a rubygems problem. However I hope this workaround will help someone with the same problem.

**Comment by lstoldt** [comment]
This fixed helped me.  Running Windows XP.

**Comment by jplarson** [comment]
Ditto that, the fixed worked like a charm.  Windows XP.

**Comment by kl** [comment]
I had the same problem and it worked for me too (also running Windows 7 64 bit). Thanks!

**Comment by timcharper** [comment]
Ugh, are you serious?  This is lame :S  I've applied this change to spork.

**Comment by jotero25** [comment]
This worked for me Windows 7 32 bit. Thanks a lot.

**Comment by AccessDenied** [comment]
Windows 7 64 bit. Working.  Thanks!

**Comment by rapcal** [comment]
Fantastic... Worked for me on XP. After 24h searching found this closed thread. Thank you very much. Using 0.9.0.rc3

**Comment by rdp** [comment]
so is this fixed in trunk?

**Comment by sudodo** [comment]
just cool... Win XP SP3 working. thank you!
