### ISSUE TITLE
Losing loaded blueprints after each step

### ISSUE THREAD

**Issue by kendagriff** [sporkrb/spork#50]
Environment: Rails 3, Cucumber, Spork, Machinist

No blueprint for class Sponsor (RuntimeError)
./features/sponsors/step_definitions/index_steps.rb:2:in `/^I have a sponsor$/'
features/schools/outreach/email.feature:8:in`And I have a sponsor'
# blueprint.rb

Sponsor.blueprint do
end

This happens AFTER the first step in a Cucumber scenario has run. In other words, the first step runs fine with Sponsor.blueprint, but on the second, spork seems to have forgotten that Sponsor.blueprint was ever defined in blueprint.rb. I've attempted to "load()" it each time in the Spork.each_run block, but it makes no difference.

Any ideas? Thanks!!

**Comment by kendagriff** [comment]
Sorry – I forgot to mention that this only happens when "cache_classes = false" in the test.rb file.

**Comment by timcharper** [comment]
Can you specifically reload it in your Spork.each_run block?  That's what I would try

Seems to be an artifact of the rails reloading mechanism.

**Comment by kendagriff** [comment]
Like so?

Spork.each_run do
  load(File.expand_path(File.dirname(**FILE**) + '/../../features/support/blueprint.rb'))
end

Doesn't seem to fix anything. Is this possibly a Rails 3 issue?

**Comment by timcharper** [comment]
Probably. If you can reproduce it in a small project, I could look into it.  May be some initialize that's not running... but hard to understand why it would work the first time, and not the subsequent times.

**Comment by kendagriff** [comment]
It's definitely something weird about my environment. I tried to reproduce the error in a fresh project, and can't. I've even seen it disappear in other Cucumber scenarios within the problematic project.

Thanks for the help!

**Comment by timcharper** [comment]
Sigh, those are the worst kinds of issues. Sorry you're having grief with spork, wish I could help!

**Comment by Juice10** [comment]
Any fix for this? I'm having the same issues

**Comment by kendagriff** [comment]
Juice10, I'm pretty sure this is not related to Spork specifically, but rather a combination of "cache_classes = false" and Machinist. I discovered that the error emerged regardless of whether I used Spork or not.

**Comment by Juice10** [comment]
Kendagriff, I actually not even using spork. My setup is steak, machinist, rspec 2, capybara. I also found out that the intensity of capybara use also determines when you get the error.
Are you also using capybara? And where you able to fix the problem? (I get totally different errors when I switch to "caches_classes = true")

**Comment by kendagriff** [comment]
To be honest, if you're not using Spork, there's really no point in switching caches_classes = false (at least that I can tell). I simply ceased using Spork alongside Machinist.
