### ISSUE TITLE
does not work with shoulda

### ISSUE THREAD

**Issue by boblin** [sporkrb/spork#56]
When I run rspec spec/models result is OK.

But when I use spork, every test where shoulda macros (like it { should validate_presence_of(:title) } are used FAILS with error like: undefined method 'validate_presence_of' for ...

rails (3.0.0)
shoulda (2.11.3)
spork (0.8.4)
rspec-rails (>= 2.0.0.beta.22)

More info here:
http://stackoverflow.com/questions/3894232/rspec-shoulda-and-spork-does-not-work-together

**Comment by timcharper** [comment]
Looks like stackoverflow community helped solve your problem.  Word on using 0.9.0.

**Comment by boblin** [comment]
with latest versions of these gems spork works without any problem:
spork (0.9.0.rc3)
rails (3.0.4)
shoulda (2.11.3)
rspec-rails (2.5.0)

**Comment by timcharper** [comment]
Great, thank you for the report.  I'll add your a link to this and your stackoverflow item to the wiki.

**Comment by medihack** [comment]
With current shoulda-matchers it is `require 'shoulda/matchers/integrations/rspec'`
