### ISSUE TITLE
Spork runs out of slaves: no tuple

### ISSUE THREAD

**Issue by lstoldt** [sporkrb/spork#58]
I have Spork working with RSpec on Windows.

Everything works great the first few times I run my tests, but then in my spork window it says "NO tuple" and "rspec spec" just returns without anymore output in the spork console.

Example: 

```
Finished in 2.61 seconds
37 examples, 3 failures
  <-- Slave(2) run done!
   -- (2);run done
   -- build slave 2...
Loading Spork.prefork block...
  --> DRb magazine_slave_service: 2 provided...
........wait a few minutes, no code changes, and run "rspec spec"..........
- NO tuple
```

spork 0.8.4
rails 3
ruby 1.9.2p0
rspec 2.0.1
autotest 4.4.1
autotest-rails 4.1.0

I'm not using autotest in this example but the problem occurs with both autotest and manually running it.

My spec/spec_helper.rb
https://gist.github.com/40f6121da00d97e106bc

**Comment by lstoldt** [comment]
I tried latest from source (0.9.0.rc2?) and got the same result.

**Comment by lstoldt** [comment]
As near as I can tell there are no problems with the processes, they're just getting lost by Rinda.

**Comment by lstoldt** [comment]
Rinda is losing the processes after exactly 3 minutes.  This change in magazine_slave_provider.rb seemed to fix it.

```
renewer = Rinda::SimpleRenewer.new
Rinda::RingProvider.new(:MagazineSlave, magazine_slave, id, renewer).provide
```

**Comment by jasonbarrows** [comment]
Istoldt, you are a genius, test suite running great (on windows) now!

**Comment by timcharper** [comment]
istoldt: should spork be patched to resolve this?

**Comment by lstoldt** [comment]
I believe so yes.

**Comment by timcharper** [comment]
I'll see if I can get Donald to comment

**Comment by tunylund** [comment]
I'm having the same issue. How's the status with this fix? Is there any way to apply a hotfix while waiting for an update?

**Comment by voxik** [comment]
Ah, I made duplicated entry as issue #90, so pasting my comment here:

Tuple entry should not expire in 3 minutes
0 comments Created 8 days ago by voxik | edit

The tuple entry expires in 3 minutes. This makes spork server useless after some period of time. I am not sure if that is something wrong in my environment but it seems that commit fixes it: https://github.com/voxik/spork/commit/980d38f642db6482be93727d3eb6fd799d43ab84

**Comment by dblock** [comment]
I made a pull request with the same, https://github.com/timcharper/spork/pull/99.

**Comment by timcharper** [comment]
Applied pull request. Will update Spork release.  Thanks!
