### ISSUE TITLE
9.0.rc2 startup failure: 9.0.rc2 startup failure: 

### ISSUE THREAD

**Issue by gregwebs** [sporkrb/spork#61]
bundle exec spork

<pre>
Using RSpec
Preloading Rails environment
undefined method `match?' for "2.3.10":String (NoMethodError)
/usr/local/lib/ruby/gems/1.8/gems/spork-0.9.0.rc2/lib/spork/app_framework/rails.rb:44:in `preload_rails'
/usr/local/lib/ruby/gems/1.8/gems/spork-0.9.0.rc2/lib/spork/app_framework/rails.rb:7:in `preload'
/usr/local/lib/ruby/gems/1.8/gems/spork-0.9.0.rc2/lib/spork/test_framework.rb:134:in `preload'
/usr/local/lib/ruby/gems/1.8/gems/spork-0.9.0.rc2/bin/../lib/spork.rb:61:in `exec_prefork'
/usr/local/lib/ruby/gems/1.8/gems/spork-0.9.0.rc2/lib/spork/test_framework.rb:120:in `preload'
/usr/local/lib/ruby/gems/1.8/gems/spork-0.9.0.rc2/lib/spork/run_strategy/forking.rb:25:in `preload'
/usr/local/lib/ruby/gems/1.8/gems/spork-0.9.0.rc2/bin/../lib/spork/runner.rb:74:in `run'
/usr/local/lib/ruby/gems/1.8/gems/spork-0.9.0.rc2/bin/../lib/spork/runner.rb:10:in `run'
/usr/local/lib/ruby/gems/1.8/gems/spork-0.9.0.rc2/bin/spork:10
/usr/local/lib/ruby/gems/1.8/bin/spork:19:in `load'
/usr/local/lib/ruby/gems/1.8/bin/spork:19
</pre>

**Comment by timcharper** [comment]
Use spork 0.8.x for rails 2.3 :)
