### ISSUE TITLE
undefined method `today' for Date:Class

### ISSUE THREAD

**Issue by tomoyuki28jp** [sporkrb/spork#62]
0.9.0.rc2 from github

gem build spork.gemspec 
ERROR:  While executing gem ... (NoMethodError)
    undefined method `today' for Date:Class

Adding `require 'date'` into the top of spork.gemspec solves this issue.

**Comment by timcharper** [comment]
seriously? Which version of ruby are you running ?

**Comment by timcharper** [comment]
added

**Comment by tomoyuki28jp** [comment]
Here is the versions I use:
rvm 1.0.20
ruby 1.9.2p0 (2010-08-18 revision 29036) [i686-linux]
