### ISSUE TITLE
Exception encountered: #<NameError: undefined local variable or method `spookie' for Spork:Module>

### ISSUE THREAD

**Issue by tomoyuki28jp** [sporkrb/spork#63]
Exception encountered: #<NameError: undefined local variable or method `spookie' for Spork:Module>
backtrace:
/home/user/app/vendor/spork-0.9.0/lib/spork.rb:152:in `after_each_run_procs'
/home/user/app/vendor/spork-0.9.0/lib/spork.rb:76:in`exec_after_each_run'
/home/user/.rvm/gems/ruby-1.9.2-p0/gems/spork-0.9.0.rc2/lib/spork/run_strategy/forking.rb:14:in `block in run'
/home/user/app/vendor/spork-0.9.0/lib/spork/forker.rb:21:in`block in initialize'
/home/user/app/vendor/spork-0.9.0/lib/spork/forker.rb:18:in `fork'
/home/user/app/vendor/spork-0.9.0/lib/spork/forker.rb:18:in`initialize'
/home/user/.rvm/gems/ruby-1.9.2-p0/gems/spork-0.9.0.rc2/lib/spork/run_strategy/forking.rb:9:in `new'
/home/user/.rvm/gems/ruby-1.9.2-p0/gems/spork-0.9.0.rc2/lib/spork/run_strategy/forking.rb:9:in`run'
/home/user/app/vendor/spork-0.9.0/lib/spork/server.rb:48:in `run'
/home/user/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1558:in`perform_without_block'
/home/user/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1518:in `perform'
/home/user/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1592:in`block (2 levels) in main_loop'
/home/user/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1588:in `loop'
/home/user/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1588:in`block in main_loop'

This commit causes this issue:
https://github.com/timcharper/spork/commit/6789317688cdebd26592e015c159ea187cff9544

**Comment by chrismdp** [comment]
I've fixed in this pull request: https://github.com/timcharper/spork/pull/65

**Comment by inspire22** [comment]
grr, pull it pretty please? :)

**Comment by chrismdp** [comment]
In the meantime you can use https://github.com/chrismdp/spork (only this patch applied)

**Comment by timcharper** [comment]
Pulled :)
