### ISSUE TITLE
Support for Merb

### ISSUE THREAD

**Issue by timcharper** [sporkrb/spork#7]
Spork will work with Merb already, but doesn't quite have the "out of the box" experience that rails does (Spork automatically hooks in to Rails to make a lot of things just work by default, like preventing your ApplicationController, views, and models from being cached).

**Comment by pk** [comment]
I'm working on the Merb support for Spork. So far I've managed to add support for Merb detection, Merb env loading so you can start Spork for Merb with the spork command.

However class reloading and running bundled project doesn't work yet.

**Comment by ysorigin** [comment]
any news about this?

**Comment by timcharper** [comment]
No news. I'm closing this, sorry.
