### ISSUE TITLE
Confusing statements regarding Rails 3 support

### ISSUE THREAD

**Issue by medihack** [sporkrb/spork#72]
In the README it says: `Rails 3.0 support is in progress, but is not ready`<br>
But then some lines below: `Supported Application Frameworks ... Rails 3.0`<br>
And it also mentions: `see the rails3 branch`. But there is no rails 3 branch.
Is Rails 3 now supported?

Thanks in advance,
Kai

**Comment by markiz** [comment]
FWIW, it works. I didn't have a single rails-specific issue yet.

**Comment by timcharper** [comment]
Resolved
