### ISSUE TITLE
Spork doesn't create slaves

### ISSUE THREAD

**Issue by Monomachus** [sporkrb/spork#76]
Hi, I'm new to RoR community and I was passing this tutorial http://railstutorial.org/chapters/static-pages#fnref:3.14

Now at work I used the same Ruby version (1.9.2) and the same Rails version(3.0.3) and everything is the same at home even the OS (Windows Vista). At work spork worked fine. At home it seems that he doesn't create slaves.

D:\rails_tutorial_project\arithmetics_test>spork
Using RSpec
  -- Rinda Ring Server listening for connections...

  -- Starting to fill pool...
     Wait until at least one slave is provided before running tests...
  *\* CTRL+BREAK to stop Spork and kill all ruby slave processes **
Spork is ready and listening on 8989!
   -- build slave 1...
   -- build slave 2...
Loading Spork.prefork block...
Loading Spork.prefork block...

And it stay like that forever

The project is here so you can see all the gems I use : http://github.com/Monomachus/arithmetics_test

I also thought that I need to install win32-process gem because it wasn't installed by default. I installed it but it changed nothing.

I also runned spork -d to diagnose it. May be now you could help me. 

D:\rails_tutorial_project\arithmetics_test>spork -d
Using RSpec
Loading Spork.prefork block...
- Spork Diagnosis -
  -- Summary --
  config/application.rb
  config/boot.rb
  config/environment.rb
  config/initializers/backtrace_silencers.rb
  config/initializers/inflections.rb
  config/initializers/mime_types.rb
  config/initializers/secret_token.rb
  config/initializers/session_store.rb
  config/routes.rb
  spec/spec_helper.rb

-- Detail --

--- config/application.rb ---
config/environment.rb:2:in `<top (required)>'
<internal:lib/rubygems/custom_require>:29:in`require'
internal:lib/rubygems/custom_require:29:in `require'
spec/spec_helper.rb:10:in`block in <top (required)>'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/spork-0.8.4/lib/spork.rb:23:in `prefo
rk'
spec/spec_helper.rb:4:in`<top (required)>'

--- config/boot.rb ---
config/application.rb:1:in `<top (required)>'
<internal:lib/rubygems/custom_require>:29:in`require'
internal:lib/rubygems/custom_require:29:in `require'
config/environment.rb:2:in`<top (required)>'
internal:lib/rubygems/custom_require:29:in `require'
<internal:lib/rubygems/custom_require>:29:in`require'
spec/spec_helper.rb:10:in `block in <top (required)>'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/spork-0.8.4/lib/spork.rb:23:in`prefo
rk'
spec/spec_helper.rb:4:in `<top (required)>'

--- config/environment.rb ---
spec/spec_helper.rb:10:in `block in <top (required)>'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/spork-0.8.4/lib/spork.rb:23:in`prefo
rk'
spec/spec_helper.rb:4:in `<top (required)>'

--- config/initializers/backtrace_silencers.rb ---
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:235:in `block in load'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:227:in`load_dependency'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:235:in `load'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/engine.rb:20
1:in`block (2 levels) in class:Engine'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/engine.rb:20
0:in `each'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/engine.rb:20
0:in`block in class:Engine'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:25:in `instance_exec'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:25:in`run'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:50:in `block in run_initializers'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:49:in`each'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:49:in `run_initializers'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application.
rb:134:in`initialize!'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application.
rb:77:in `method_missing'
config/environment.rb:5:in`<top (required)>'
internal:lib/rubygems/custom_require:29:in `require'
<internal:lib/rubygems/custom_require>:29:in`require'
spec/spec_helper.rb:10:in `block in <top (required)>'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/spork-0.8.4/lib/spork.rb:23:in`prefo
rk'
spec/spec_helper.rb:4:in `<top (required)>'

--- config/initializers/inflections.rb ---
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:235:in `block in load'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:227:in`load_dependency'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:235:in `load'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/engine.rb:20
1:in`block (2 levels) in class:Engine'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/engine.rb:20
0:in `each'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/engine.rb:20
0:in`block in class:Engine'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:25:in `instance_exec'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:25:in`run'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:50:in `block in run_initializers'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:49:in`each'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:49:in `run_initializers'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application.
rb:134:in`initialize!'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application.
rb:77:in `method_missing'
config/environment.rb:5:in`<top (required)>'
internal:lib/rubygems/custom_require:29:in `require'
<internal:lib/rubygems/custom_require>:29:in`require'
spec/spec_helper.rb:10:in `block in <top (required)>'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/spork-0.8.4/lib/spork.rb:23:in`prefo
rk'
spec/spec_helper.rb:4:in `<top (required)>'

--- config/initializers/mime_types.rb ---
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:235:in `block in load'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:227:in`load_dependency'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:235:in `load'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/engine.rb:20
1:in`block (2 levels) in class:Engine'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/engine.rb:20
0:in `each'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/engine.rb:20
0:in`block in class:Engine'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:25:in `instance_exec'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:25:in`run'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:50:in `block in run_initializers'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:49:in`each'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:49:in `run_initializers'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application.
rb:134:in`initialize!'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application.
rb:77:in `method_missing'
config/environment.rb:5:in`<top (required)>'
internal:lib/rubygems/custom_require:29:in `require'
<internal:lib/rubygems/custom_require>:29:in`require'
spec/spec_helper.rb:10:in `block in <top (required)>'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/spork-0.8.4/lib/spork.rb:23:in`prefo
rk'
spec/spec_helper.rb:4:in `<top (required)>'

--- config/initializers/secret_token.rb ---
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:235:in `block in load'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:227:in`load_dependency'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:235:in `load'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/engine.rb:20
1:in`block (2 levels) in class:Engine'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/engine.rb:20
0:in `each'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/engine.rb:20
0:in`block in class:Engine'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:25:in `instance_exec'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:25:in`run'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:50:in `block in run_initializers'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:49:in`each'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:49:in `run_initializers'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application.
rb:134:in`initialize!'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application.
rb:77:in `method_missing'
config/environment.rb:5:in`<top (required)>'
internal:lib/rubygems/custom_require:29:in `require'
<internal:lib/rubygems/custom_require>:29:in`require'
spec/spec_helper.rb:10:in `block in <top (required)>'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/spork-0.8.4/lib/spork.rb:23:in`prefo
rk'
spec/spec_helper.rb:4:in `<top (required)>'

--- config/initializers/session_store.rb ---
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:235:in `block in load'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:227:in`load_dependency'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:235:in `load'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/engine.rb:20
1:in`block (2 levels) in class:Engine'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/engine.rb:20
0:in `each'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/engine.rb:20
0:in`block in class:Engine'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:25:in `instance_exec'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:25:in`run'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:50:in `block in run_initializers'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:49:in`each'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:49:in `run_initializers'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application.
rb:134:in`initialize!'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application.
rb:77:in `method_missing'
config/environment.rb:5:in`<top (required)>'
internal:lib/rubygems/custom_require:29:in `require'
<internal:lib/rubygems/custom_require>:29:in`require'
spec/spec_helper.rb:10:in `block in <top (required)>'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/spork-0.8.4/lib/spork.rb:23:in`prefo
rk'
spec/spec_helper.rb:4:in `<top (required)>'

--- config/routes.rb ---
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:235:in `block in load'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:225:in`block in load_dependency'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:596:in `new_constants_in'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:225:in`load_dependency'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/dependencies.rb:235:in `load'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application.
rb:127:in`block in reload_routes!'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application.
rb:127:in `each'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application.
rb:127:in`reload_routes!'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application.
rb:120:in `block in routes_reloader'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/file_update_checker.rb:32:in`call'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_suppor
t/file_update_checker.rb:32:in `execute_if_updated'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application/
finisher.rb:51:in`block (2 levels) in module:Finisher'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application/
finisher.rb:52:in `call'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application/
finisher.rb:52:in`block in module:Finisher'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:25:in `instance_exec'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:25:in`run'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:50:in `block in run_initializers'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:49:in`each'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/initializabl
e.rb:49:in `run_initializers'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application.
rb:134:in`initialize!'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.3/lib/rails/application.
rb:77:in `method_missing'
config/environment.rb:5:in`<top (required)>'
internal:lib/rubygems/custom_require:29:in `require'
<internal:lib/rubygems/custom_require>:29:in`require'
spec/spec_helper.rb:10:in `block in <top (required)>'
C:/rubies/Ruby192/lib/ruby/gems/1.9.1/gems/spork-0.8.4/lib/spork.rb:23:in`prefo
rk'
spec/spec_helper.rb:4:in `<top (required)>'

--- spec/spec_helper.rb --- 

Thanks and I hope you can help me to see the difference.

P.S. I also worth mentioning that I modified magazine_slave_provider.rb line (5) from require 'magazine_slave' to require './magazine_slave'

**Comment by timcharper** [comment]
Please flag down Donald Parish https://github.com/Milhouse or Roger Pack https://github.com/rdp for assistance with this issue.

**Comment by timcharper** [comment]
Oh shoot... I didn't mean to close this... no way to undo :S  Sorry!
