### ISSUE TITLE
JRuby: you must call Spork.using_spork! before starting the server

### ISSUE THREAD

**Issue by jpshackelford** [sporkrb/spork#79]
I receive the following backtrace when executing spork against spork-0a437df35201 (0.9.0.rc2) and JRuby 1.5.3. I have run $ bundle exec spork --bootstrap and followed the instructions there.

```
$ bundle exec spork
Using RSpec
-- Starting to fill pool...
   Wait until at least one slave is provided before running tests...
** CTRL+BREAK to stop Spork and kill all ruby slave processes **
you must call Spork.using_spork! before starting the server (RuntimeError)
/home/shacjo/.rvm/gems/jruby-1.5.3/bundler/gems/spork-0a437df35201/lib/spork/server.rb:25:in `listen'
/home/shacjo/.rvm/gems/jruby-1.5.3/bundler/gems/spork-0a437df35201/lib/spork/server.rb:20:in `run'
/home/shacjo/.rvm/gems/jruby-1.5.3/bundler/gems/spork-0a437df35201/bin/../lib/spork/runner.rb:75:in `run'
/home/shacjo/.rvm/gems/jruby-1.5.3/bundler/gems/spork-0a437df35201/bin/../lib/spork/runner.rb:10:in `run'
/home/shacjo/.rvm/gems/jruby-1.5.3/bundler/gems/spork-0a437df35201/bin/spork:10
/home/shacjo/.rvm/gems/jruby-1.5.3/bundler/gems/spork-0a437df35201/bin/spork:19:in `load'
/home/shacjo/.rvm/gems/jruby-1.5.3/bin/spork:19
```

Note that I did discover that the following line was commented out: http://github.com/timcharper/spork/blob/master/lib/spork/run_strategy/magazine/magazine_slave.rb#L14

It is unclear to me whether something else should be calling Spork.using_spork! or whether this is the correct place for it and it was inadvertently disabled.

Thanks for your help

**Comment by jpshackelford** [comment]
I verified that removing the comment from the line mentioned above does not improve the situation.

**Comment by rdp** [comment]
is this supposed to still be open?

**Comment by jpshackelford** [comment]
Yes. Thanks!

**Comment by ghost** [comment]
is it resolved?

**Comment by voxik** [comment]
This is completely broken by this commit :( 

https://github.com/timcharper/spork/commit/9421aaceb027b36eb199c243df918f2d24b3da28

**Comment by voxik** [comment]
Hm, for windows and JRuby just comment out this line:

https://github.com/timcharper/spork/blob/master/lib/spork/server.rb#L25

Its not fix, just workaround ...
