### ISSUE TITLE
debugger() produces internal error from ruby-debug

### ISSUE THREAD

**Issue by rjharmon** [sporkrb/spork#8]
INTERNAL ERROR!!! wrong argument type DRb::DRbObject (expected File)
        /Library/Ruby/Gems/1.8/gems/ruby-debug-0.10.3/cli/ruby-debug/interface.rb:112:in `readline'
        /Library/Ruby/Gems/1.8/gems/ruby-debug-0.10.3/cli/ruby-debug/interface.rb:112:in`readline'
        /Library/Ruby/Gems/1.8/gems/ruby-debug-0.10.3/cli/ruby-debug/interface.rb:62:in `read_command'
        /Library/Ruby/Gems/1.8/gems/ruby-debug-0.10.3/cli/ruby-debug/processor.rb:246:in`process_commands'
        /Library/Ruby/Gems/1.8/gems/ruby-debug-0.10.3/cli/ruby-debug/processor.rb:171:in `__at_line'
        (eval):5:in`at_line'
        (eval):3:in `synchronize'
        (eval):3:in`at_line'
        /Library/Ruby/Gems/1.8/gems/ruby-debug-base-0.10.3/lib/ruby-debug-base.rb:54:in `at_line'
        ./spec/views/designs/new.html.haml_spec.rb:28
        /Library/Ruby/Gems/1.8/gems/actionpack-2.3.2/lib/action_controller/assertions/selector_assertions.rb:309:in`assert_select'
       [trimmed]

**Comment by timcharper** [comment]
This is not so much a spork bug, but an issue in the test server protocol.  The client sends over it's output streams via drb, and on the server side they don't come out as IO streams but DRb objects that act like IO streams.

To fix this we will need to revisit the test server protocol, and get the client to pass the actual IO stream file descriptors over a Unix socket.

**Comment by rjharmon** [comment]
I don't mind debugging in the terminal where I started spork, in case that's helpful.

**Comment by timcharper** [comment]
That's a possibility.  The way things are rigged up though now is STDOUT and STDERR are passed through DRb.  There would need to be some significant haxoring on rspec I believe to get it to output to a stream other than STDOUT (It may do that already though... I don't know).

I'm excited to work on Spork again but am super busy preparing for my LSRC 2009 training course.  So, as soon as LSRC is over I plan on resuming Spork development.

Tim

**Comment by timcharper** [comment]
This has been implemented... a while ago :) (0.7 I think).

**Comment by btelles** [comment]
Hi Tim,
I'm still encountering this error with the latest version (0.7.3) Anyone else out there seeing this?

**Comment by timcharper** [comment]
perhaps it wasn't made very clear.  You must require 'spork/ext/ruby-debug'.  

See the feature for an example:

http://github.com/timcharper/spork/blob/master/features/spork_debugger.feature

**Comment by btelles** [comment]
Poifect! Thanks!
