### ISSUE TITLE
Windows fix #80

### ISSUE THREAD

**Issue by gehan** [sporkrb/spork#91]
I had an import error, I got it to work as below (commented out bad line 4)

https://gist.github.com/839729

**Comment by timcharper** [comment]
Thanks, this change is already made in the most recent version of spork

https://github.com/timcharper/spork/blob/196e05e511b57e4f750568ddb6a73ea1d44e21c0/lib/spork/run_strategy/magazine/magazine_slave_provider.rb#L5
