### ISSUE TITLE
warning: already initialized constant DEFAULT_PORT + HELPER_FILE

### ISSUE THREAD

**Issue by grimen** [sporkrb/spork#93]
<pre>/Users/grimen/.rvm/gems/ruby-1.9.2-p0@xxx/gems/spork-0.9.0.rc2/lib/spork/test_framework/cucumber.rb:2: warning: already initialized constant DEFAULT_PORT
/Users/grimen/.rvm/gems/ruby-1.9.2-p0@xxx/gems/spork-0.9.0.rc2/lib/spork/test_framework/cucumber.rb:3: warning: already initialized constant HELPER_FILE
/Users/grimen/.rvm/gems/ruby-1.9.2-p0@xxx/gems/spork-0.9.0.rc2/lib/spork/test_framework/rspec.rb:2: warning: already initialized constant DEFAULT_PORT
/Users/grimen/.rvm/gems/ruby-1.9.2-p0@xxx/gems/spork-0.9.0.rc2/lib/spork/test_framework/rspec.rb:3: warning: already initialized constant HELPER_FILE
</pre>

Quite annoying...

**Comment by grimen** [comment]
Actually this is gone in "rc4" it seems. Had to uninstall all rc:s to avoid rc2 to be loaded, ignored any newer versions even after bundle update. =S Anyway, close this one.

**Comment by rapcal** [comment]
Happening with rc4 for me...

**Comment by bitflorist** [comment]
+1 on 0.9.0 rc8

**Comment by nel** [comment]
+1 on 0.9.0 rc8

**Comment by robertcigan** [comment]
+1 0.9.0.rc8

**Comment by RobertDeRose** [comment]
+1 0.9.0.rc9  

if I just run spork alone

works perfectly if I run it with 

bundle exec spork
